### ISSUE TITLE
When there is one entity in a group, it is not displayed

### ISSUE THREAD

**Issue by Aledan862** [nielsfaber/scheduler-card#103]
Config example
```
- type: custom:scheduler-card
  standard_configuration: true
  discover_existing: false
  title: false
  include:
    - light
    - switch.watering_valve
  groups:
    - name: "Освещение"
      icon: outdoor-lamp
      include:
        - light.vkhod
    - name: "Клапаны"
      icon: sprinkler-variant
      include:
        - switch.watering_valve
```

![image](https://user-images.githubusercontent.com/40725083/95002304-b1d92080-05d2-11eb-9734-b440ba157e12.png)

Although I can continue creating the schedule, this behavior is very confusing.

![image](https://user-images.githubusercontent.com/40725083/95002362-578c8f80-05d3-11eb-971c-596a3a4b7fb4.png)
