### ISSUE TITLE
trouble with installation

### ISSUE THREAD

**Issue by mjsambol** [nielsfaber/scheduler-card#123]
Hi I am stuck on the installation. I have HomeAssistant installed directly on a raspberry venv, am not using HassOS. I have the scheduler integration showing up OK, but am not able to get the scheduler card to show up.

I saved the .js file in .homeassistant/www/scheduler-card/
I added the following lines to my configuration.yaml:

```
lovelace:
  mode: yaml
  resources:
    - url: /local/scheduler-card/scheduler-card.js?v=0
      type: module

```

In ui-lovelace.yaml I added just one line, to the list of cards in an existing dashboard:

      - type: custom:scheduler-card

After a restart, in the UI where I hoped to see the card I get:

Custom element doesn't exist: scheduler-card.
type: 'custom:scheduler-card'

in the log file I have:

https://<trimmed>/local/scheduler-card/scheduler-card.js?v=0:1:1 Uncaught SyntaxError: Unexpected token '<'

help?

**Comment by KTibow** [comment]
What happens if you go to `/local/scheduler-card/scheduler-card.js?v=0`? You should really stop using lovelace YAML and manual installation, use hacs by typing in `curl -sfSL https://hacs.xyz/install | bash -` to your home assistant command line.

**Comment by nielsfaber** [comment]
The error message indicates that the first character in the scheduler-card.js file is a `<`.
In the actual file, it’s a `!`.
Make sure this file is used:
https://github.com/nielsfaber/scheduler-card/blob/master/dist/scheduler-card.js

And change the end of the url to `?v=1`.
And click reload resources in HA.

That should do the job

**Comment by mjsambol** [comment]
Thank you for the quick replies. It seems that somehow I had a download of the github webpage rather than the js code. The result, I guess, of working on this too late at night. 

I am now able to see the scheduler card, but not to get any entities to show up on it. With just the one line of configuration 

`      - type: custom:scheduler-card
`
The card shows "There are no groups defined". So I added configuration:

```
      - type: custom:scheduler-card
        standard_configuration: false
        include:
          - switch.upstairs_ac_power
        groups:
          - name: "AirCon"
            include:
              - switch.upstairs_ac_power

```
Still I have "There are no groups defined". 

By the way, copy-pasting from the documentation at https://github.com/nielsfaber/scheduler-card led to an error: the docs indicate 

`If you would rather set up your own configuration of entities and actions, you can provide standard_configuration:false to disable it.
`
added that way, I get an error from HA. There should be a space after the colon.

I'd appreciate any suggestion as to why my entities aren't being discovered or accepted from configuration. The switch that I provided in manual config is a template switch, in case that's relevant.
