### ISSUE TITLE
Custom action is overwritten by the default one

### ISSUE THREAD

**Issue by mkowalczuk** [nielsfaber/scheduler-card#135]
I have the following action defined:
```
            actions:
              - service: climate.set_temperature
                name: heat to temperature
                icon: mdi:thermometer-plus
                service_data:
                  hvac_mode: heat
                variable:
                  field: temperature
                  name: Temperature
                  min: 8
                  max: 28
```

When I select it as an action for my entity, the next time I edit the schedule, it falls back to the default "Set temperature".
