### ISSUE TITLE
media_player entities not showing up

### ISSUE THREAD

**Issue by claudegel** [nielsfaber/scheduler-card#155]
I've this in my config:
```
- name: "Musique"
            icon: music
            include:
              - media_player.bureau
              - media_player.chalet
              - media_player.salon
              - media_player.garage
```
but none are showing in Music group. Are they normally available in scheduler-card ?
