### ISSUE TITLE
Card disappears when clicking on "New item"

### ISSUE THREAD

**Issue by mycortex** [nielsfaber/scheduler-card#158]
Version: 1.8.2

When loading my dashboard the card shows all my schedules in the card and it looks like it should. But as soon as I click the NEW ITEM-button the card completely disappears from the dashboard. When reloading the page it comes back showing my schedules as it was before clicking NEW ITEM.

Config:
```
type: 'custom:scheduler-card'
include:
  - fan
  - light
  - switch
  - climate
groups:
  - name: 'Light/switch'
    include:
      - light
      - switch
  - name: 'Climate/fan'
    include:
      - fan
      - climate
```
