### ISSUE TITLE
[feature request] Allow custom attributes to be added to newly created schedule entities

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#237]
Scheduler component creates new entities, with random ```entity_id```-s. To select these entities in scripts is really painful. Eg. I want to turn off all schedules that belong to thermostats, but not for irrigation. If (admin) users create new, random named/identified switch entities, it is hard to select them. See [How to use custom tests in Jinja template?](https://community.home-assistant.io/t/how-to-use-custom-tests-in-jinja-template/247904) The suggested method is to add custom attributes to the entities.

A simple new card configuration would make it easy, to filter scheduler entities in scripts, something like:
```
type: 'custom:scheduler-card'
...
custom_attributes:
  - schedule_type: thermostat
  - my_custom_attribute_2_name: "my_custom_attribute_2_value"
  - my_custom_attribute_3_name: "my_custom_attribute_3_value"
```
This is backward compatible. Any new schedule entity created by this card will have these extra custom attributes. So not only schedules are easily separated from switches, but we can even distinguish between schedules created by different cards! Seems to be quite powerful. In a script's template we could write:
```
{{ states.switch|selectattr('attributes.schedule_type', 'eq', 'thermostat')|map(attribute='entity_id')|list }}
```
