### ISSUE TITLE
Feature Request: Incorporate Workday Binary Sensor

### ISSUE THREAD

**Issue by Jonah1970** [nielsfaber/scheduler-card#27]
Hi,

I currently use a bunch of input_datetime's in my heating controls as shown below and was wondering if I could use your new schedular component to simplify this.

![image](https://user-images.githubusercontent.com/53110372/92701305-b7cb4100-f347-11ea-8efb-06f4a8860db9.png)

I currently make use of HA's Workday Binary Sensor (essentially to turn the heating on later at weekends and holidays) and was wondering whether you might consider incorporating an option to have the workday entity being on or off as a criteria rather than manually selecting days of the week.

https://www.home-assistant.io/integrations/workday/

Cheers!

**Comment by nielsfaber** [comment]
Hi,
I think the scheduler could definitely simplify things for you.
Currently the way it works is you choose for which days + time you want to trigger an action, so in your case you could make a schedule for weekdays and a schedule for weekends.
In the near future it will become possible to combine these separate schedules into one.
Having this functionality in place, I doubt that reading the weekday sensor adds anything extra.
Cheers!

**Comment by Jonah1970** [comment]
Hi,

Many thanks for the speedy response, can I just check that you understand the significance and flexibility that the Worday binary sensor in HA provides.  As an example, this is my config:
```
- platform: workday
  name: Workday
  country: UK
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays: 
    - '2021-10-26'
    - '2021-10-27'
    - '2021-10-28'
    - '2021-10-29'
    - '2021-10-30'
    - '2021-11-02'
    - '2021-11-03'
    - '2021-11-04'
    - '2021-11-05'
    - '2021-11-06'
    - '2021-12-18'
    - '2021-12-21'
    - '2021-12-22'
    - '2021-12-23'
    - '2021-12-24'
    - '2021-12-28'
    - '2021-12-29'
    - '2021-12-30'
    - '2021-12-31'
```
This means that any UK national holiday (country: UK) and any of my nominated work holidays (add_holidays:) set the Workday sensor false meaning that these are effectively treated like weekends even though they are week days.  Great if you don't want the heating to come on when you are on holiday and it prevents the need to tweak around with the schedule every time you are off work.

If I used your scheduler to setup schedules for Mon-Fri and Sat/Sun as you suggest then how can I cater for public holidays which often occur on Mondays/Fridays or for work holidays.  I realise that I can manually modify the time setting but more often than not I would probably forget to do so.

It occurred to me the HA Workday sensor makes this easy and it could potentially make your scheduler more flexible.

This is just a suggestion and I fully understand if you feel this is beyond the scope of what you wanted to achieve.

Thanks again!
