### ISSUE TITLE
Possible to get the next action scheduled?

### ISSUE THREAD

**Issue by z4rn0x** [nielsfaber/scheduler-card#283]
Hello
Instead of listing all coming modes and actions on my dashboard, I'm trying to create a display of the next action / time among all my schedules (one single line for the very next trigger)...
Easy for the time (`{{ state_attr('switch.schedule_402594', 'next_trigger') }}` and a sensor: min/max), but I can't get a way to have the name of the action that will be triggered... Is it a limitation of the plugin or is there a way to do it?
Thanks for the help!

**Comment by nielsfaber** [comment]
The actions are in attributes of the schedule entity, e.g.:
```
actions: 
- service: light.turn_on
  entity_id: light.dining_lights
  service_data:
    brightness: 79
```
So for a schedule with single action it would be easy to retrieve it.

For schedules with multiple time slots this is more problematic, since you would need to know which of the actions comes next. 
Unfortunately there is nothing in place for this.
