### ISSUE TITLE
Add option to activate scenes/automations

### ISSUE THREAD

**Issue by anarro** [nielsfaber/scheduler-card#30]
If you can add the opcions to select scenes and automations form UI.

**Comment by nielsfaber** [comment]
You can already do this!
It’s a matter of defining a domain configuration in YAML for `scene` and `automation`, along with the HA services you want to be available.
It is currently not part of the standard configuration (since I don’t think the majority of users will use the scheduler in this way), but it can easily be expanded.
If you need help setting it up, let me know!
Also in the forum people are willingly to share their solutions 👍

**Comment by anarro** [comment]
Ouuu perfect! 

Please, is this settings correct?

```
type: 'custom:scheduler-card'
domains:
  scene:
    actions:
      - service: apply
  light:
    actions:
      - service: turn_on
      - service: turn_off
  cover:
    actions:
      - service: open
      - service: close
      - service: position
        name: set position
        variable:
          field: position
          name: Position
          showPercentage: true
```

Thank you very match,

**Comment by nielsfaber** [comment]
Hi, no problem!
For `scene` you can use the `turn_on` and `turn_off` services. `apply` would require many more parameters.
You can read about it here: https://www.home-assistant.io/integrations/scene/

The `light` actions should be already there as standard config, so you can leave them out.

For `cover` you should recheck your service names. It should be `open_cover`, `close_cover` and `set_cover_position`.
You can check it here: https://www.home-assistant.io/integrations/cover/
Please add `max: 100` to the variable config, since the default range is 0-255. 

After these updates, all should work!

**Comment by anarro** [comment]
I love this card, thanks you!


```
type: 'custom:scheduler-card'
discoverExisting: true
standardConfiguration: true
domains:
  scene:
    actions:
      - service: apply
        name: execute
        icon: play-box
  light:
    actions:
      - service: turn_off
        icon: lightbulb-off
      - service: turn_on
        icon: lightbulb-on-outline
        variable:
          field: brightness
          name: Brightness to
          min: 0
          max: 255
  cover:
    actions:
      - service: open
        icon: window-shutter-open
      - service: close
        icon: window-shutter
      - service: set_cover_position
        name: set position
        icon: window-shutter-alert
        variable:
          field: position
          name: Position to
          showPercentage: true

```

Antoni
