### ISSUE TITLE
When creating multiple scheduler-card all schedules apears in all cards

### ISSUE THREAD

**Issue by thygeL** [nielsfaber/scheduler-card#300]
I have the "show all schedules" setting to off
ver: 2.0.4

thyge

**Comment by KTibow** [comment]
Please elaborate. Share YAML config?

**Comment by thygeL** [comment]
my lovelace yaml

views:
  - title: Temperature
    path: temperature
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.hjem
        secondary_info_attribute: wind_speed
        name: Vejrudsigten
      - type: entities
        entities:
          - entity: sensor.vaerksted_temperatur
          - entity: sensor.nodered_1798a5c5_4acfea
          - entity: sensor.nodered_73b8cf95_9308f
  - title: Lys
    path: lys
    badges: []
    cards:
      - type: light
        entity: light.wled
      - type: light
        entity: light.sonoff_100024406b
      - type: entities
        entities:
          - entity: switch.sonoff_basic_relay
          - entity: sensor.sonoff_basic_wifi_signal
          - entity: binary_sensor.sonoff_basic_button
          - entity: light.sonoff_basic_green_led
        state_color: true
  - title: Termostater
    path: termostater
    badges: []
    cards:
      - type: thermostat
        entity: climate.thermostat_2
      - type: thermostat
        entity: climate.thermostat_4
  - title: Lys styring
    path: scheduler
    badges: []
    cards:
      - type: 'custom:scheduler-card'
        discover_existing: false
        title: Lys
        time_step: 1
        include:
          - light
          - switch
  - title: Varmestyring
    path: varmestyring-2
    panel: true
    badges: []
    cards:
      - type: grid
        columns: 4
        cards:
          - type: 'custom:scheduler-card'
            discover_existing: false
            include:
              - climate
            title: Thyge's kontor
          - type: 'custom:scheduler-card'
            discover_existing: false
            title: Stue
            include:
              - climate
          - type: 'custom:scheduler-card'
            title: Helle's kontor
            discover_existing: false

**Comment by KTibow** [comment]
Please use the `<>` button.

**Comment by thygeL** [comment]
`views:
  - title: Temperature
    path: temperature
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.hjem
        secondary_info_attribute: wind_speed
        name: Vejrudsigten
      - type: entities
        entities:
          - entity: sensor.vaerksted_temperatur
          - entity: sensor.nodered_1798a5c5_4acfea
          - entity: sensor.nodered_73b8cf95_9308f
  - title: Lys
    path: lys
    badges: []
    cards:
      - type: light
        entity: light.wled
      - type: light
        entity: light.sonoff_100024406b
      - type: entities
        entities:
          - entity: switch.sonoff_basic_relay
          - entity: sensor.sonoff_basic_wifi_signal
          - entity: binary_sensor.sonoff_basic_button
          - entity: light.sonoff_basic_green_led
        state_color: true
  - title: Termostater
    path: termostater
    badges: []
    cards:
      - type: thermostat
        entity: climate.thermostat_2
      - type: thermostat
        entity: climate.thermostat_4
  - title: Lys styring
    path: scheduler
    badges: []
    cards:
      - type: 'custom:scheduler-card'
        discover_existing: false
        title: Lys
        time_step: 1
        include:
          - light
          - switch
  - title: Varmestyring
    path: varmestyring-2
    panel: true
    badges: []
    cards:
      - type: grid
        columns: 4
        cards:
          - type: 'custom:scheduler-card'
            discover_existing: false
            include:
              - climate
            title: Thyge's kontor
          - type: 'custom:scheduler-card'
            discover_existing: false
            title: Stue
            include:
              - climate
          - type: 'custom:scheduler-card'
            title: Helle's kontor
            discover_existing: false
`

**Comment by KTibow** [comment]
Use 3 backticks, and put them on their own line.

**Comment by thygeL** [comment]
I now shure what you mean ?

**Comment by KTibow** [comment]
This thing is called a backtick: `
Use 3 of them, like this: ```
Put that on a line without anything else. Then press the enter key. Then paste your code. Then press the enter key, Then add 3 more.

**Comment by thygeL** [comment]
```
views:
  - title: Temperature
    path: temperature
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.hjem
        secondary_info_attribute: wind_speed
        name: Vejrudsigten
      - type: entities
        entities:
          - entity: sensor.vaerksted_temperatur
          - entity: sensor.nodered_1798a5c5_4acfea
          - entity: sensor.nodered_73b8cf95_9308f
      - type: entities
        entities:
          - entity: sensor.bme280_temperature
          - entity: sensor.bme280_pressure
          - entity: sensor.bme280_relative_humidity
          - entity: sensor.dew_point
  - title: Lys
    path: lys
    badges: []
    cards:
      - type: light
        entity: light.wled
      - type: light
        entity: light.sonoff_100024406b
      - type: entities
        entities:
          - entity: switch.sonoff_basic_relay
          - entity: sensor.sonoff_basic_wifi_signal
          - entity: binary_sensor.sonoff_basic_button
          - entity: light.sonoff_basic_green_led
        state_color: true
  - title: Termostater
    path: termostater
    badges: []
    cards:
      - type: thermostat
        entity: climate.thermostat_4
      - type: thermostat
        entity: climate.thermostat_3
      - type: thermostat
        entity: climate.thermostat_5
  - title: Lys styring
    path: scheduler
    badges: []
    cards:
      - type: 'custom:scheduler-card'
        discover_existing: false
        title: Lys
        time_step: 1
        include:
          - light
          - switch
  - title: Varmestyring
    path: varmestyring-2
    panel: true
    badges: []
    cards:
      - type: grid
        columns: 4
        cards:
          - type: 'custom:scheduler-card'
            discover_existing: false
            include:
              - climate
            title: Thyge's kontor
          - type: 'custom:scheduler-card'
            discover_existing: false
            title: Stue
            include:
              - climate
          - type: 'custom:scheduler-card'
            title: Helle's kontor
            discover_existing: false
```
