### ISSUE TITLE
Public holiday ignored when working with workday sensor

### ISSUE THREAD

**Issue by ntompson** [nielsfaber/scheduler-card#343]
I'm loving the simplicity that this card provides compared to automating time based triggers in yaml, but today I discovered that a public holiday was ignored, even though I have the workday sensor configured and working. It's hard to pin down what's gone wrong, as previous testing during a public holiday worked fine.

First, confirmation that the workday sensor is configured and working (today, Monday 8 March, which is a public holiday in Tasmania).

```yaml
binary_sensor:
  - platform: workday
    country: AU
    province: TAS
    add_holidays:
      # Royal Hobart Regatta
      - '2021-02-08'
      - '2022-02-14'
      - '2023-02-13'
      # Royal Hobart Show
      - '2021-10-21'
      - '2022-10-20'
      - '2023-10-26'
```

Confirming that the sensor detected today as public holiday:

<img width="416" alt="Screen Shot 2021-03-08 at 9 38 58 am" src="https://user-images.githubusercontent.com/32885870/110257449-1e2cd580-7ff2-11eb-97e1-53d2886cc178.png">

But this morning, one of my workday tasks was triggered:

<img width="445" alt="Screen Shot 2021-03-08 at 9 40 35 am" src="https://user-images.githubusercontent.com/32885870/110257502-57654580-7ff2-11eb-8fed-d6612b9b504c.png">

Which is configured as follows:

<img width="508" alt="Screen Shot 2021-03-08 at 9 41 33 am" src="https://user-images.githubusercontent.com/32885870/110257537-795ec800-7ff2-11eb-89c9-e4679cbb2b0f.png">

I also noticed that, in the days leading up to the public holiday, the "next task" secondary info in the main scheduler GUI screen indicated tasks running / not running on the basis that Monday would be a workday, not a public holiday.

Making it more difficult to diagnose, I *think* that as soon as I change something (eg add a task / modify a task), the bug disappears. Perhaps this causes scheduler to reload stuff (I don't know what) and in doing so, reassesses the workday sensor. 

So today, after noticing that the public holiday had been missed, I added a new task configured for workday and it correctly showed that first run would be tomorrow. Not only that, but the *other* existing tasks also showed correct next run times.

It would be great if this can be fixed as I need to be able to rely on workdays being correctly detected - the family don't like to be woken early on a public holiday!!

Thanks for your great work
