### ISSUE TITLE
Card not found after upgrading to v2.1.0

### ISSUE THREAD

**Issue by kaizersoje** [nielsfaber/scheduler-card#374]
I get an error that the card is not found after upgrading to v 2.1.0.

I downgraded back to v 2.0.5 and the card is found again. I am currently on HA 2021.4.6

**Comment by nielsfaber** [comment]
Are you using HACS?
If so, can you check in your config folder whether www/community/scheduler-card/scheduler-card.js exists?
Also, is anything printed in the browser logs?

**Comment by jadson179** [comment]
try clear cache in the browser and reload page

**Comment by balbulator** [comment]
I have the same problem, after the update, the map disappeared in the Lovelace view

**Comment by balbulator** [comment]
Nothing has changed in the config file
`  - url: /hacsfiles/scheduler-card/scheduler-card.js
    type: module`
the file in the folder is also present
`config\www\community\scheduler-card`

**Comment by balbulator** [comment]
Rollback to version 2.0.5 helped, everything returned

**Comment by nielsfaber** [comment]
@kaizersoje 
> Yes, I am using HACS. After upgrading, the scheduler-card.js disappeared and there was only a zip file in the folder.

This is strange.
HACS should unpack the zip and place the .js file there.
If that doesn't happen, you could manually unpack it and refresh the frontend (Click "Reload resources"):
![image](https://user-images.githubusercontent.com/16861605/116726594-ca33e100-a9e3-11eb-97b3-6bf1caa85d5d.png)

**Comment by nielsfaber** [comment]
Could you try updating to v2.1.1?
It contains some bug fixes introduced by the v2.1.0, none of which are actually related to this, but perhaps it was an issue with the last release.

**Comment by balbulator** [comment]
2.1.1 - all right, thank you

**Comment by balbulator** [comment]
Sorry, but the problem with the missing image remained in versions 2.1.0 and 2.1.1
Works fine only in 2.0.5

**Comment by balbulator** [comment]
Without rebooting the home assistant, version 2.1.1 is working, I'm afraid to reboot, the last time after rebooting the card disappeared

**Comment by balbulator** [comment]
In the last two versions, after a reboot, the card disappears, so far nothing helps, a rollback coma to 2.0.5

**Comment by nielsfaber** [comment]
Seems like you have a different issue than others.
Maybe it is due some schedule you have configured.
You could help me by checking the browser logs when it occurs.
See here on how to access them for your browser: https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs
Please post the results here.

**Comment by balbulator** [comment]
Hooray, everything worked out, I just updated the HACS and everything was fine, now the card does not disappear after a reboot. Thank you for your willingness to help, the issue is closed.

**Comment by nielsfaber** [comment]
@kaizersoje Any updates on the status of this issue?
Im not sure how I can help. I don’t have clues so far that it’s actually in the code.

**Comment by balbulator** [comment]
everything repeated again - no map
now I will try to remove the logs

**Comment by balbulator** [comment]
```
Uncaught (in promise) TypeError: Cannot read property 'some' of undefined
    at s (scheduler-card.js:351)
    at scheduler-card.js:351
    at Array.some (<anonymous>)
    at Ts (scheduler-card.js:351)
    at scheduler-card.js:387
    at Array.every (<anonymous>)
    at scheduler-card.js:387
    at Array.every (<anonymous>)
    at scheduler-card.js:387
    at Array.forEach (<anonymous>)
```
`scheduler-card.js:351`

**Comment by nielsfaber** [comment]
This error seems related to your card config.
Did you set up some custom groups or something else specific?

**Comment by balbulator** [comment]
yes, I created individual groups
groups:
  - light
  - switch
  - vacuum
  - cover
  - sensor
  - ***

**Comment by balbulator** [comment]
```
  - title: Plan
    id: scheduler
    icon: mdi:calendar-clock

    cards:

      - type: custom:scheduler-card
        groups:
          - name: "Light"
            icon: ceiling-light
            include:
              - light
              - switch.sonoff_10007f0bca_1
              - switch.sonoff_10007f0bca_2

          - name: "Switch"
            icon: nintendo-switch
            include:
              - switch

          - name: "Vacuum"
            icon: robot-vacuum
            include:
              - vacuum

          - name: "Cover"
            icon: blinds
            include:
              - cover
              - script.blinds_down
              - script.blinds_up

          - name: "Sensors light"
            icon: weather-sunny
            include:
              - sensor.0x00158d00045fa2a5_illuminance
              - sensor.0x00158d00049fcfa6_illuminance
              - sensor.0x00158d00045f7a5a_illuminance
              - sensor.0x04cf8cdf3c776274_illuminance_lux
              - sensor.0x04cf8cdf3c7769e9_illuminance_lux
              - sensor.0x00158d00042cfb84_illuminance

          - name: "Sensors motion"
            icon: motion-sensor
            include:
              - binary_sensor.0x00158d00045fa2a5_occupancy
              - binary_sensor.0x00158d00049fcfa6_occupancy
              - binary_sensor.0x00158d00045f7a5a_occupancy
              - binary_sensor.0x00158d000461cebf_occupancy
              - binary_sensor.0x00158d00042cfb84_occupancy

          - name: "Sensors windows"
            icon: window-closed
            include:
              - binary_sensor.0x00158d00045c15f3_contact
              - binary_sensor.0x00158d00049fb06c_contact
              - binary_sensor.door_window_sensor_158d0004314266
              - binary_sensor.door_window_sensor_158d00049fdc76
              - binary_sensor.0x00158d00049fb4dd_contact

          - name: "Sensors temperature"
            icon: thermometer
            include:
              - sensor.0x00158d00045bd991_temperature
              - sensor.0x00158d0004210d2d_temperature
              - sensor.temperature_158d00045c2ea8
              - sensor.0x00158d0004657cc6_temperature

          - name: "Sensors humidity"
            icon: water-percent
            include:
              - sensor.0x00158d00045bd991_humidity
              - sensor.0x00158d0004210d2d_humidity
              - sensor.humidity_158d00045c2ea8
              - sensor.0x00158d0004657cc6_humidity
```

**Comment by balbulator** [comment]
But it was like this from the start and it worked great.

**Comment by ASNNetworks** [comment]
I had the same issue, I reverted back which solved it. Clearing cache did not solve it. I will try again, perhaps because variables have change, it now doesn't load with old settings. Though I did double check and I don't use any changed settings, so it should work fine. I will report back once I have had time to test more. 

Currently running 2.0.5 version.

**Comment by nielsfaber** [comment]
I'm quite sure you have found a bug due to changes I've done in my code.
I (and many others) don't define their own groups, I will run some tests myself to catch the problem.

**Comment by nielsfaber** [comment]
It seems like i made the `exclude` declaration mandatory for each group.
I was able to reproduce (and fix) the problem by adding it manually:
```yaml
groups:
  - name: "my group"
    include:
      - switch.my_entity
      - ...
    exclude: [] # add this line as quick-fix
```
If you want to run the latest version you could add it manually (for each group).

Ofcourse I will plan a release to fix this problem.
