### ISSUE TITLE
Change of variables type in customize

### ISSUE THREAD

**Issue by MarkusHornbach** [nielsfaber/scheduler-card#380]
After breaking change in scheduler-card 2.1.0 declaration `variable` was not only changed to `variables`, seems also the type has also changed from` map` to `list` (of maps)?
If this is the case it should be adapted in the documentation.

**Comment by nielsfaber** [comment]
You’re absolutely right.
It’s a map with the fields to be provided in the service_data as keys.
I don’t like bringing breaking changes, but this one was needed for the flexibility that comes with it.
I updated the documentation to show the format that is needed, see here:
https://github.com/nielsfaber/scheduler-card#numeric-action-variable

example:
```
customize:
  fan.xiaomi_purifier:
    actions:
      - service: xiaomi_miio.fan_set_favorite_level
        name: "set speed"
        variables:
          level:
            name: "Speed"
            min: 1
            max: 16
```
If you think the documentation is not clear or misses something, feel free to contribute!
(For me all is clear, since I made it..)

**Comment by MarkusHornbach** [comment]
sorry, I did not change documentation myself because I'm not sure whether I'm right in my assumption.
old:
```...
  variable:
     level:
       name: "Speed"
       min: 1
       max: 16
```
new:
```...
  variables:
     - level:
         name: "Speed"
         min: 1
         max: 16
```
Is this correct?

**Comment by nielsfaber** [comment]
As you said, `variables` is now a map, so don't use dashes for indexing:
```
  variables:
     level:
       name: "Speed"
       min: 1
       max: 16
```

**Comment by hobbypunk90** [comment]
Hello @nielsfaber,

i thought your documentation is clear, but when the numeric variable ist correct, is this a typo?
```yaml
        variables: hvac_mode
          name: Operation mode
          options:
            - value: heat
              icon: "hass:fire"
            - value: cool
              icon: "hass:snowflake"
            - value: "off"
              icon: "hass:power"
```

I think i have a little mistake in my config, can you please have a look?

```yaml
type: 'custom:scheduler-card'
time_step: 5
include:
  - input_number
  - vacuum.wassissn
display_options:
  secondary_info:
    - '{days} {time}'
customize:
  vacuum.wassissn:
    actions:
      - service: script.clean_room
        name: Raum saugen
        icon: ''
        variables:
          room:
            name: Raum
            options:
              - value: Arbeitszimmer
                icon: 'hass:laptop'
              - value: Wohnzimmer
                icon: 'hass:sofa'
              - value: Schlafzimmer
                icon: 'hass:bed'
              - value: Bad
                icon: 'hass:water-pump'
              - value: Küche
                icon: 'hass:fridge'
              - value: Flur
                icon: 'hass:rug'
          speed:
            name: Modus
            options:
              - value: '101'
                name: Leise
              - value: '102'
                name: Ausgeglichen
              - value: '103'
                name: Turbo
              - value: '104'
                name: Maximum
              - value: '105'
                name: Wischen
```

**Comment by nielsfaber** [comment]
@hobbypunk90 
Second part looks ok to me.
In the first part you wrote
> variables: hvac_mode

this should be written as
```
variables:
  hvac_mode:
```

**Comment by hobbypunk90** [comment]
that's what i expected.
But the action don't shows up 😒  is there any kind of debug mode, so i can look for the problem?

**Comment by nielsfaber** [comment]
@hobbypunk90 

> But the action don't shows up

Which one exactly? You posted quite a few.
Regarding `hvac_modes`, they are only showing up if your climate entity actually _supports_ them (otherwise filtered out).

**Comment by hobbypunk90** [comment]
@nielsfaber sorry, it was a bit messy.
The action with hvac_mode ist only from the doc.
The second code block is my config 😅
This should be one action. Before your 2.1.0 update i had a config with a fixes speed and a room AS variable. Now, since there are multiple options possible i tried to switch to set both variables as variable 🙂

**Comment by MarkusHornbach** [comment]
now I got finally this map issue. I was confused by the "field" element which was a key string before, but now this should be ok:

'''
customize:
  climate.*:
    actions:
      - service: script.climate_set
        name: Set mode
        variables:
          mode:
            name: Operation mode
            options:
              - value: heating
              - value: eco
              - value: 'off'
      - service: script.climate_set
        name: Set temp
        service_data:
          mode: temp
        variables:
          target_temp:
            name: Target temp
            min: 10
            max: 25
            step: 0.5
'''
But unfortunately I cannot see any variable names in the GUI.
![climate_set](https://user-images.githubusercontent.com/38568564/117199316-58480700-adea-11eb-80ce-c3edadb9d8bc.png)

**Comment by nielsfaber** [comment]
@hobbypunk90 @MarkusHornbach 
both of your configs look OK to me, so I would expect would get the variables available for picking.
If this is not the case, I would have to try it for myself, see what’s going on.

I’m afraid I don’t have time for this until the weekend though.

**Comment by hobbypunk90** [comment]
@nielsfaber thank you 😊

**Comment by MarkusHornbach** [comment]
@nielsfaber : I would like to help you debugging, but about programming TypeScript I have absolutely no idea, sorry. With python it would rather go ;-)

**Comment by kaizersoje** [comment]
I am trying to set the volume level of my media device. However, I am not seeing the volume level slider.

```
type: 'custom:scheduler-card'
discover_existing: false
groups:
  - name: Media Players
    icon: cast
    include:
      - media_player.bed_spot
      - media_player.nesthub
customize:
  media_player.bed_spot:
    actions:
      - service: media_player.volume_set
        name: set volume
        icon: volume-medium
        variables:
          volume_level:
            name: Level
            min: 0
            max: 1
            step: 0.01
title: Media Devices
```

This is what it looks like.

![image](https://user-images.githubusercontent.com/54566217/117398902-ad972c00-af42-11eb-8206-3c8b73ffd455.png)

**Comment by nielsfaber** [comment]
@hobbypunk90 
I have trouble to reproduce the issue you're having.
I copied your code (assigned it to a switch though), the result looks OK:
![image](https://user-images.githubusercontent.com/16861605/117480973-99fbbd80-af62-11eb-8f98-19028aa12e38.png)

Same for @MarkusHornbach  and @kaizersoje .
I can copy your codes and it works out of the box.

Apparently I made some changes in the meantime which solved this (accidentally), i will work on a release for it.

**Comment by MarkusHornbach** [comment]
ok, behaviour changed, but it is still buggy. When I have two services defined ("Set mode" + "Set temp"), the first one "Set mode" overwrites the second one, so when "Set temp" is choosen, options from "Set mode" are displayed. If only one service is defined, it works fine:
```
customize:
  climate.*:
    actions:
      - service: script.climate_set
        name: Set mode
        variables:
          mode:
            name: Operation mode
            options:
              - value: heating
              - value: eco
              - value: 'off'
      - service: script.climate_set
        name: Set temp
        service_data:
          mode: temp
        variables:
          target_temp:
            name: Target temp
            min: 10
            max: 25
            step: 0.5
```
![image](https://user-images.githubusercontent.com/38568564/117553655-15d53300-b053-11eb-913f-526acb10b874.png)
