### ISSUE TITLE
Custom actions not showing

### ISSUE THREAD

**Issue by rousveiga** [nielsfaber/scheduler-card#392]
Hello! I defined a custom action for `climate` entities, and it doesn't appear in the card; only the default actions (turn off, heat, cool) show. My config is below - am I overlooking something?

```yaml
  - type: custom:scheduler-card
    title: Horario calefacción
    time_step: 5
    include:
      - climate
    customize:
      climate:
        actions:
          - service: climate.set_temperature
            name: Comfort
            service_data:
              temperature: 21
            icon: "mdi:sofa-single"
```

I've tried using a specific entity under `customize`, and got the same results. I've cleared the cache as well. My card version is 2.1.1.
