### ISSUE TITLE
"No entities in group" with standard_configuration: false

### ISSUE THREAD

**Issue by rousveiga** [nielsfaber/scheduler-card#394]
Hello! I set `standard_configuration` to `false` because I wanted to customize my actions. I'm trying to get all my `climate` entities in the same group:

```yaml
- type: custom:scheduler-card
  title: Horario calefacción
  standard_configuration: false
  time_step: 5
  include:
    - climate
  groups:
    - name: "Climatización"
      icon: "mdi:home-thermometer-outline"
      include:
        - climate
```

However, no entities show up in the group:

![image](https://user-images.githubusercontent.com/11377258/117790002-35ce4780-b249-11eb-9ae0-8fd823934b26.png)

Am I overlooking something?

My card version is 2.1.2.

Thanks in advance.
