### ISSUE TITLE
Custom card is not showing

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/scheduler-card#4]
Keep running into the following error in the chrome dev console with a fresh/new install of your custom integration and card.
Tried installing through HACS, this puts the file in the HACS rootfolder instead of its own 'scheduler-card' folder. Then tried cloning the git folder into the /local/ folder and setting it up according to your github page. Still no luck, the card will never show up and keeps throwing the error below in the chrome dev console.

```
Version 3.109.0 
entitylist.js:12 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Entitylist.Parselist (entitylist.js:12)
    at HTMLElement.set hass [as hass] (scheduler-card.js?v=0:32)
    at HTMLElement.value (chunk.c136a66895309b59c3fe.js:23707)
    at HTMLElement.value (chunk.c136a66895309b59c3fe.js:24142)
    at HTMLElement.t.addEventListener.once (chunk.c136a66895309b59c3fe.js:23707)
    at n (app.664a8247.js:1)
    at chunk.c136a66895309b59c3fe.js:13138
```

This is my lovelace yaml btw, its a copy of your example, but with my working entity_id:
```yaml
type: 'custom:scheduler-card'
entities:
  light.tv_meubel_2:
    name: "TV Meubel"
    icon: ceiling-light
    actions: 
      - service: turn_on
        service_data:
          brightness: 100
        name: "Turn on at 40%"
        icon: lightbulb-on-outline
      - service: turn_off
        icon: lightbulb-off-outline 
```

**Comment by nielsfaber** [comment]
Hi Bob,
Nice to hear you want to use my scheduler integration.
The bad news is that it is still in beta, so there are some quirks here and there.
Please check out my comment about this in the HA forum: https://community.home-assistant.io/t/scheduler-card-custom-component/217458/14
Basically what it comes down to is that you have to include the ‘groups’ and ‘domains’ in your config as well, they are currently required inputs.
The rest looks good to me, so could you just try to follow the instructions in the link and see if it helps?

**Comment by bobvmierlo** [comment]
Hmm i've done the following, not really clear on what to put in the config.yaml.
The information on the custom integration is not telling me anything about putting something in the config.yaml

Lovelace card yaml:
```yaml
domains:
  light:
    actions:
      - service: turn_on
      - service: turn_off
type: 'custom:scheduler-card'
```

configuration.yaml:
```yaml
scheduler:
  domains:
    light:
      actions:
        - service: turn_on
        - service: turn_off
```
