### ISSUE TITLE
Slider is broken when unit of measurement is "%"

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#401]
Scheduler v3.1.1
Card v2.1.2 (browser cache deleted)
HA 2021.5.3 OS

Test config:
```yaml
input_number:
  test:
    min: 40
    max: 80
    name: Test
    unit_of_measurement: "%"
```

How to replicate:
- add schedule, select "Set value" action, use the slider

Bug:
- slider can move 0 to 100% (not 40 to 80%)
- values out of min/max range are stored in the schedule, but displayed only a value within the range
  - with above example, you can set a value of 23%, it is stored in the schedule, though only "40%" is displayed everywhere
