### ISSUE TITLE
Standard configuration is broken for humidifier

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#404]
Scheduler v3.1.2
Card v2.1.3 (browser cache deleted)
HA 2021.5.4 OS

I'm aware of #76, #82, #210, that this is in a "semi public" state.

I'm using home-assistant/core#36759 (yeah, generic_hygrostat is still not merged).

cc: @KTibow from #82

Problem: even if I add

```yaml
type: 'custom:scheduler-card'
include:
  - humidifier
```

or

```yaml
type: 'custom:scheduler-card'
include:
  - humidifier.some_concrete_entity
```

Nothing shows up when I try to add a new schedule:

![image](https://user-images.githubusercontent.com/5061219/118375040-73233400-b5bf-11eb-82d6-7205f36acc58.png)

I have to add the actions also:

```yaml
include:
  - humidifier
customize:
  humidifier:
    actions:
      - service: set_humidity
        icon: 'hass:water-percent'
        name: 'set humidity[ to {humidity}]'
        variables:
          humidity:
            name: Humidity
            unit: '%'
            min: 40
            max: 80
            step: 1
```

So I think something is broken, if the default settings/actions are there, but not working.
