### ISSUE TITLE
Custom states not working

### ISSUE THREAD

**Issue by doogie-at** [nielsfaber/scheduler-card#405]
hi,
I'm trying to use the customize section to enable non-integer states for sensors, e.g. "rainy" as a condition
Somehow, no matter what I try, non numeric states always turn up as slider 0-255.

My card configuration 

```
customize:
  sensor.openweathermap_forecast_condition:
    name: weather
    states:
      - rainy
      - clear
```

the sensor is now named "weather", so I at least did not mistype it.
But the states don't show up, still only 0 - 255

tried it with different sensors, with same result

I'm using HASS CORE 2021.5.0 and scheduler component and card (v2.1.3) from HACS

any help much appreciated...
BR 
Doogie

**Comment by nielsfaber** [comment]
In the v2.1.3 update some things were changed related to this.
From what you describe, the behaviour matches with v2.1.2 (or earlier) of the card.
It looks like you have a cache issue.
Please open the developer tools of the browser and confirm the card version:
![image](https://user-images.githubusercontent.com/16861605/118758805-06829080-b870-11eb-98ad-480080b12411.png)

**Example of current behaviour**

Sensor config:
```
  - platform: template
    sensors:
      sun_state:
        friendly_name: "Sun State"
        value_template: >
          {% if is_state('sun.sun', 'above_horizon') %}
            up
          {% else %}
            down
          {% endif %}
```

Card config:
```
customize:
  sensor.sun_state:
    states:
      - above_horizon
      - below_horizon
```

Result:
![image](https://user-images.githubusercontent.com/16861605/118758641-b3a8d900-b86f-11eb-982f-d9006852874d.png)
