### ISSUE TITLE
Bug : start when it's not need

### ISSUE THREAD

**Issue by roumano** [nielsfaber/scheduler-card#408]
Hi,

Sometimes, the sceduler start when it's not need :

* I have create this climate entry :
```
  - platform: generic_thermostat
    unique_id: climate.poeles
    name: 'Poêles Hoben'
    heater: switch.poele
    target_sensor: sensor.sonde_salon_temperature
    min_temp: 15
    max_temp: 23
    ac_mode: false
    target_temp: 20.0
    cold_tolerance: 1.0
    hot_tolerance: 1
    min_cycle_duration:
      minutes: 120
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 17
    precision: 0.1
```

* i have set, via shedular card, to have 20°c today this morning at 7h00 :

![scheduling](https://user-images.githubusercontent.com/6402894/118780480-6129e580-b88c-11eb-855d-59175edf4d06.png)

* Normaly as the temperautre of `sensor.sonde_salon_temperature` was 20.3°, normaly it's shouln't start  : 
![history_sonde_temp](https://user-images.githubusercontent.com/6402894/118780580-7f8fe100-b88c-11eb-8618-e8efc3d6c61c.png)

But, today, as exemple, it's was start, on my logs i see this (sorry it's in french but it easy to understand ) : 
```
Poêles Hoben changé en Chauffe. par le service climate.set_hvac_mode
7:00:00 - Il y a 19 minutes
```

I use the lastest version available via HACS :
- Scheduler component : `v.3.1.2`
- Scheduler Card : `v2.1.3`
