### ISSUE TITLE
exclude_actions is partially broken for humidifier

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#424]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Remove standard config action from the actions list.

### Actual behavior
It stayed there.

### Steps to Reproduce
Scheduler v3.1.3
Card v2.1.4 (browser cache deleted)
HA 2021.6.5 OS

Test config:
```yaml
type: custom:scheduler-card
standard_configuration: true
discover_existing: false
include:
  - humidifier.dehumidifier_hygrostat
customize:
  humidifier.dehumidifier_hygrostat:
    exclude_actions:
      - set mode
      - set humidity
      - turn on
      - turn off
```

`turn on` and `turn off` works as expected, but `set mode` and `set humidity` doesn't, these 2 actions remain in the list. I've tried with `mode` and `humidity` only, no change. Certainly removing everything makes no sense, I wanted to remove `set mode` only, discovered the bug, then tested everything. This line should work, so I don't know what is the problem.
```
actions = actions.filter(e => !e.name || !excludedActions.some(a => parseString(e.name!).includes(a)));
```
