### ISSUE TITLE
Fractional temperatures saved as whole

### ISSUE THREAD

**Issue by mjsambol** [nielsfaber/scheduler-card#427]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
When creating a schedule for a thermostat, using the temperature slider I can choose a half-degree value, and this should be saved with the schedule.

### Actual behavior
The UI saves only whole degree values. Even without saving, simply going into the options tab and then hitting back, the half-degree value previously selected has been replaced with a whole degree value.

### Steps to Reproduce
I've indicated 0.5 for step size in configuration, and confirmed that my climate entity's configuration matches that:

```
climate:
  - platform: dualmode_generic
...
    min_temp: 16
    max_temp: 30
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
        minutes: 8
    precision: 0.5
```

and in my lovelace configuration I'm using the script you've provided [in your README](https://github.com/nielsfaber/scheduler-card#triggering-multiple-actions-on-a-schedule) with:

```
                      temperature:
                        name: Temperature
                        min: 16
                        max: 30
                        step: 0.5
```

I can provide a screencast of this in action if that's helpful.
