### ISSUE TITLE
Climate set temperature rounded to whole numbers, though the slider selects values based on the thermostat precision

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#447]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

Scheduler v3.1.3
Card v2.1.4 (browser cache deleted)
HA 2021.9.5 OS

### Expected behavior
Use the selected value, do not round it (previously it worked correctly).

### Actual behavior
The slider selects a non-whole value, but when the slider is released, a whole value is displayed and stored in the schedule.

If I edit the storage file and "enter" a non-whole value, this value will be used.

### Steps to Reproduce

Sample config:
``` yaml
climate:
  - platform: generic_thermostat
    name: Heater thermostat
    heater: input_boolean.heater_thermostat_switch
    target_sensor: sensor.living_room_temperature_average_for_heater
    min_temp: 5
    max_temp: 30
    ac_mode: false
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 10
    away_temp: 18
    precision: 0.1
```
``` yaml
type: custom:scheduler-card
include:
  - climate.heater_thermostat
```

Select action "Heat", Next, move the temperature slider, it uses 0.1 precision, but when it is released, it will be rounded to an integer value.
