### ISSUE TITLE
CRITICAL BUG: Turned off schedule schemas activated by HA core restart!!!

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-card#449]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
When a schedule scheme is turned off, it should not do anything even on restart. Previously it worked as expected. __Now after a restart the system state is a complete mess, heating system, exhaust fans, lights, everything is turned on in my house!!!__

### Actual behavior
It put the target entity in the scheduled state. When I deleted the schedule, the target entity's did not changed after HA core restart. I repeated this test multiple times, the presence of the turned off schedule was the reason.

### Steps to Reproduce

Create an input_boolean.test
``` yaml
input_boolean:
  test:
    name: Test
```

Add a scheduler card:
``` yaml
  - type: custom:scheduler-card
    include:
      - input_boolean.test
```

Suppose you set up this schedule (attributes):
```
weekdays: daily
times: 00:00:00, 14:00:00, 14:30:00
actions: 
- service: input_boolean.turn_off
  entity_id: input_boolean.test
- service: input_boolean.turn_on
  entity_id: input_boolean.test

current_slot: 1
next_slot: 2
next_trigger: 2021-09-10T14:30:00+02:00
tags: 
friendly_name: Schedule #05f418
icon: mdi:calendar-clock
```

__TURN OFF the schedule and the input select!!!__

If you restart the system between 14:00 and 14:30, it will turn on the input_select!!!
