### ISSUE TITLE
Custom action name not remembered

### ISSUE THREAD

**Issue by meks007** [nielsfaber/scheduler-card#451]
Hi,

Custom action name is only available while editing a schedule but will not affect how the schedule is displayed after it is saved.

```yml
customize:
  light.my_lamp:
    name: "Dining light"
    icon: "hass:ceiling-light"
    actions:
      - service: turn_on
        service_data:
          brightness: 100 # note that brightness is from 0-255 so 100 = 40%
        name: "Turn on at 40%"
        icon: "hass:lightbulb-on-outline"
```

"Turn on at 40%" can be selected while creating a new schedule. After that schedule is saved it only shows as "Turn on". When you edit the schedule, the correct (customized) name shows up but is not considered as being selected.
