### ISSUE TITLE
Add {operation_mode} to Display Options

### ISSUE THREAD

**Issue by timdonovanuk** [nielsfaber/scheduler-card#482]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
For entities that use an operation mode, it would make sense to be able to see that in the card UI, rather than the {action}. 

Consider a water_heater.hot_water entity. The action is "Set mode" but the **operation_mode sets the actual true action, e.g. 'on' or 'off'.**

The way this currently ends up displaying is:

![image](https://user-images.githubusercontent.com/8156439/144253928-59d22d14-9d92-4a21-aed7-41e2a43101c1.png)

What would be far more useful is to see the operation_mode, e.g.:

![image](https://user-images.githubusercontent.com/8156439/144254061-ec6713f6-6240-4c34-8cbd-649030851098.png)

If it helps, here is my current setup:

```
type: custom:scheduler-card
discover_existing: false
time_step: 30
title: Scheduler
display_options:
  primary_info:
    - '{entity}'
  secondary_info:
    - 'Next: {action} {time}'
  icon: hass:action
include:
  - water_heater.hot_water
  - climate.babyroom
customize:
  water_heater.hot_water:
    name: Hot Water
    icon: mdi:water-pump
    actions:
      - service: water_heater.set_operation_mode
        name: 'Set Mode'
        icon: water-pump
        variables:
          operation_mode:
            name: Operation mode
            options:
              - value: auto
                icon: mdi:refresh-auto
              - value: heat
                icon: hass:fire
                name: 'On'
              - value: 'Off'
                icon: hass:fire-off
                name: 'Off'
```
Thanks for this amazing component, this should have been part of core HA for years!

**Comment by timdonovanuk** [comment]
Realised now using this with a climate entity that perhaps my hot water is not setup right with this card. I think perhaps this card doesn't work automatically with water_heater.set_operation_mode ? Unlike climate.set_preset_mode where it seems to understand modes.

I somehow need to move water_heater Operation Mode to look like Actions.

**Comment by nielsfaber** [comment]
I believe the 'built in' support for water_heater entities is incomplete and can be improved to fix your problem.
I will take a look and see if I can create some 'dummy' entity locally to test the behaviour.

**Comment by nielsfaber** [comment]
I made some changes in the card to improve the support for water_heater entities.
Operation modes are now showing up ok:
![image](https://user-images.githubusercontent.com/16861605/144753479-ba323904-551c-4709-ac47-8b83c6052eaa.png)

In the overview card you will see the correct description for the upcoming action as well:
![image](https://user-images.githubusercontent.com/16861605/144753490-2f3b4ae9-e212-4033-90d9-545242a4db8d.png)

I will let you know when a new release is out with these changes.

**Comment by nielsfaber** [comment]
Your issue should be fixed by updating to v2.3.0. 
Please test it out and close the issue if this is the case (otherwise please let me know).

**Comment by timdonovanuk** [comment]
Thanks @nielsfaber super appreciated! Coffee's sent :)

Almost working, the actions and operations doesn't match up to water_heater.hot_water entity. 

The operations available on my water_heater.hot_water entity is:

![image](https://user-images.githubusercontent.com/8156439/145566800-7b8cf1ab-a839-424b-bcd1-7d1e9b907b42.png)

But the scheduler shows all sorts of operations (and none seem to be auto or heat):

![image](https://user-images.githubusercontent.com/8156439/145566957-7df92b70-f484-4bce-994b-722180cf9687.png)

A few other issues:

- In the image above there is also two "Set Mode" actions, with the same list of operations
-
![image](https://user-images.githubusercontent.com/8156439/145567169-2be8df8f-8f17-446b-9e0b-935c410cbf94.png)

- The "Set Mode to Off" action also lets me set an operation

![image](https://user-images.githubusercontent.com/8156439/145567331-96889bc4-a6a4-4611-8337-d02c28a14c34.png)

- There are two OFF operations listed

![image](https://user-images.githubusercontent.com/8156439/145567384-72c2092c-1495-412b-b36c-7fe1fb7ca542.png)

If I can help out with any more details or info or testing please let met know!

Cheers.

**Comment by nielsfaber** [comment]
Thanks for your coffees, I appreciate it! 🙏 
I realise now didn't read your initial issue description well enough, else I could have foreseen this.
The modes (aka states) that scheduler expects/supports are listed [here](https://developers.home-assistant.io/docs/core/entity/water-heater/#states).
Your component (I'm guessing Tado?) seems to introduced new ones, which struck me by surprise.
I have never seen a component deviate from the states defined by HA (which is sort of the 'holy bible' for me when it comes to implementing features in a generic way) and I have the feeling that your integration is the bad guy in this case by not following the definition.
I have to think about how to (/whether) deal with this, because this scenario might occur also for other entity types than just `water_heater`, so the required changes to handle this also go a bit further.

In the meantime I'm afraid you have to work with the customization you had earlier.
Some small comments on this:
```yaml
customize:
  water_heater.hot_water:
    name: Hot Water
    icon: mdi:water-pump
    actions:
      - service: water_heater.set_operation_mode
        name: 'Set Mode[ to {operation_mode}]' # this makes the mode show up in the overview
        icon: water-pump
        variables:
          operation_mode:
            name: Operation mode
            options:
              - value: auto
                icon: mdi:refresh-auto
              - value: heat
                icon: hass:fire
                name: 'On'
              - value: 'off' # not sure if 'Off' is handled the same as 'off'
                icon: hass:fire-off
                name: 'Off'
```
FYI: for next time, I also added a small example about such customizations in the [documentation](https://github.com/nielsfaber/scheduler-card#customizing-built-in-actions). I know the documentation is not everything, but you seemed already very close to fixing it yourself 😉
