### ISSUE TITLE
Condition: can't use 0 value as threshold

### ISSUE THREAD

**Issue by haseat** [nielsfaber/scheduler-card#487]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.0

### Component Version

v3.2.4

### Bug description

I wanted to make a condition for an input_number with "value above 0". Unfortunately, the Save button is greyed out when the value is 0 (works fine with values greater than 0).

![image](https://user-images.githubusercontent.com/61622258/145663170-f65da714-7e1a-495e-aebf-7544735d48dd.png)
![image](https://user-images.githubusercontent.com/61622258/145663216-99bd2a82-1309-4172-a7db-cc11a5c03d11.png)

I noticed a closed ticket with the same problem and tried the suggested solution, but it does not work for me:

```
type: custom:scheduler-card
title: Heating Schedules Bathroom
time_step: 15
include:
  - binary_sensor
  - climate
  - group
  - input_boolean
  - input_number
  - light
tags:
  - Heating Bathroom
display_options:
  primary_info: name
  secondary_info: '{relative-time}: {action}'
  icon: entity
discover_existing: false
customize:
  input_number.activities_bathroom_boost_heating_counter:
    states:
      min: 0
      max: 100
      step: 1
```

### Steps to reproduce

Add an input_number as an condition and try "value above 0".
