### ISSUE TITLE
Scheme slider is permanently stuck

### ISSUE THREAD

**Issue by ConnorThomp** [nielsfaber/scheduler-card#491]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.0

### Component Version

v3.2.4

### Bug description

I am using the scheduler card within a custom button card in order to keep it looking the same as everything else on my dashboard.

This seems to have created an issue with the scheme slider, as when I select the slider to adjust the time I cannot deselect it, rendering the card useless. 

This issue only occurs when using the scheduler card within a custom button card.

Below is the yaml I am using in order to replicate this issue, along with a clip of the issue described.

```
type: custom:button-card
custom_fields:
  graph:
    card:
      type: custom:scheduler-card
      entity: climate.thermostat
      include:
        - climate
        - water_heater
      exclude: []
      display_options:
        primary_info: default
        secondary_info:
          - relative-time
        icon: action
      discover_existing: true
      title: Heating Schedule
      time_step: 10
      tags: []
      style: |
        ha-card {
          box-shadow: none;
          border-radius: 0%;
          background-color: transparent;
        }
styles:
  custom_fields: null
  card:
    - background-color: transparent
    - box-shadow: none
    - border-radius: 0%
    - padding: 5%
    - padding-top: 3%
  grid:
    - grid-template-areas: '"i" "n" "graph"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
    - background-color: '#202020'
tap_action:
  action: more-info
```

https://gyazo.com/d6a19ba0b66055a64a34786e977b8af8

### Steps to reproduce

To reproduce this issue you will need to have custom button card installed.

You can then use the following yaml to reproduce the issue described above, though you will likely need to adjust the entities within the yaml for it to work with your setup.

```
type: custom:button-card
custom_fields:
  graph:
    card:
      type: custom:scheduler-card
      entity: climate.thermostat
      include:
        - climate
        - water_heater
      exclude: []
      display_options:
        primary_info: default
        secondary_info:
          - relative-time
        icon: action
      discover_existing: true
      title: Heating Schedule
      time_step: 10
      tags: []
      style: |
        ha-card {
          box-shadow: none;
          border-radius: 0%;
          background-color: transparent;
        }
styles:
  custom_fields: null
  card:
    - background-color: transparent
    - box-shadow: none
    - border-radius: 0%
    - padding: 5%
    - padding-top: 3%
  grid:
    - grid-template-areas: '"i" "n" "graph"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
    - background-color: '#202020'
tap_action:
  action: more-info
```
