### ISSUE TITLE
entity icon

### ISSUE THREAD

**Issue by NNois** [nielsfaber/scheduler-card#492]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Hi,
on the latest version
Many of my Zigbee devices are considered as Light but they are not, ex: SONOFF devices
I can set a custom icon on the entity.
But the icon displayed in the scheduler cart as it's considered a light remains a light icon.

Is there a possibility to show the current entity icon ?

### Additional info

I tried the display option but the icon section doesn't change anything... changing primary_info is working
```
display_options:
  primary_info:
    - "{entity}: {action}"
    - additional-tasks
  secondary_info: relative-time
  icon: "hass:entity"
```

![image](https://user-images.githubusercontent.com/2362053/146339443-14c1066a-fc9a-461e-8e64-38d575d0219e.png)
![image](https://user-images.githubusercontent.com/2362053/146339503-a3a19b01-4014-4a54-b36e-0765a48c0444.png)
![image](https://user-images.githubusercontent.com/2362053/146339550-12ceb2a3-0e89-4674-9418-99279d1569a5.png)
