### ISSUE TITLE
Feature request: set position for covers

### ISSUE THREAD

**Issue by nagyrobi** [nielsfaber/scheduler-card#50]
Just like for a climate you can set the temperature, have for covers not only open and close, but also set position.

**Comment by nielsfaber** [comment]
I did not add it, because `set_position` is not always possible with a `cover` (depends on the device).
It is similar to `light` entities in HA, not are dimmable.
From [what i can see](https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py#L70), the `supported_features` property could be used to check if a `cover` is position controllable.
I could add such check (it is already in place for `light` entities).

**Comment by nagyrobi** [comment]
Thank you.

**Comment by anarro** [comment]
Hi,

I'm sorry but with the previous version I have this option!, I use the set_position with a covers entity..., but now this option dosen't work..

**Comment by nielsfaber** [comment]
@anarro please share details if something broke in a recent release.
Nothing is changed in v1.3.0 or v1.2.8 that should affect this functionality, so i am curious what causes your problem.

**Comment by anarro** [comment]
mmm look this screenshot... the light dosen't work too.. and I just update this morning..


<img width="510" alt="Captura de pantalla 2020-09-19 a las 11 28 27" src="https://user-images.githubusercontent.com/8436433/93663907-5f90ef00-fa6b-11ea-9b59-f4b43c7f57ce.png">



this is my config:

```
discoverExisting: true
domains:
  cover:
    actions:
      - icon: window-shutter-open
        service: open
      - icon: window-shutter
        service: close
      - icon: window-shutter-alert
        name: set position
        service: set_cover_position
        variable:
          field: position
          name: Position to
          showPercentage: true
  light:
    actions:
      - icon: lightbulb-off
        service: turn_off
      - icon: lightbulb-on-outline
        service: turn_on
        variable:
          field: brightness
          max: 255
          min: 0
          name: Brightness to
  scene:
    actions:
      - icon: play-box-multiple
        service: apply
  script:
    actions:
      - icon: play-box-multiple
        name: trigger
        service: turn_on
standardConfiguration: true
title: Programacion Scripts
type: 'custom:scheduler-card'
```
