### ISSUE TITLE
Scheduler-card "forgets" to display customized actions

### ISSUE THREAD

**Issue by gvssr** [nielsfaber/scheduler-card#504]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.0

### Component Version

3.2.6

### Bug description

Scheduler-card seems to "forget" to display customized actions with re-editing a schedule.

### Steps to reproduce

- Use yaml to add customized actions
- Use those action(s) in a schedule
- Save schedule
- Reopen saved schedule

### Additional info

**Example**:

When creating a schedule with custom actions it displays properly (note the buttons for Comfort, Eco, Sleep, Away):
![image](https://user-images.githubusercontent.com/61377476/149809739-b613422d-0192-44a6-b315-8be37d8401c6.png)

Then when you save it and reopen the same schedule, they're gone:
![image](https://user-images.githubusercontent.com/61377476/149809840-bba2179d-b17e-4c24-b474-79d36ce04a94.png)

**Yaml used:**
```
  climate.studiekamer_radiator:
    name: Studiekamer Radiator
    icon: mdi:radiator
    actions:
      - service: script.generic_component_climate
        name: Generic Modes
        icon: mdi:thermostat
        service_data:
          climate:
            entity_id: climate.studiekamer_radiator
        variables:
          mode:
            name: Mode
            options:
              - value: Comfort
                icon: mdi:fire
              - value: Eco
                icon: mdi:leaf
              - value: Sleep
                icon: mdi:sleep
              - value: Away
                icon: mdi:snowflake
```

**Comment by nielsfaber** [comment]
I have seen this issue before, thought I fixed it.
It's definitely a bug (and fixable), I would have to look into it.
How does it look like in the schedule items list? Are you seeing the correct icon here?

BTW: consider renaming the action to:
```
name: "Set generic mode[ to {mode}]"
```

It would cause the Comfort/Eco setting etc. to be displayed in the card (once this bug is tackled)

**Comment by gvssr** [comment]
@nielsfaber Thanks for the tip, I changed it. Here are a couple of screenshots, hope it helps:

The schedule when configured in the list:
![16AC03EA-2C03-4FBF-AF61-198B1962308B](https://user-images.githubusercontent.com/61377476/150011608-c1bd303c-cf03-44e0-acda-55b3cf0b6052.jpeg)

The schedule as is when opened after it’s correctly configured (this one contains multiple modes):
![911A73E2-AD48-493A-AD1B-E83D686ED826](https://user-images.githubusercontent.com/61377476/150011611-fc4b9785-c330-4bf7-9380-412347998a19.jpeg)

The action it displays:
![FFFAA1C4-946F-42FA-AE56-34B5FFEBF57B](https://user-images.githubusercontent.com/61377476/150011613-ca9a35b0-8759-4c03-bf05-f5c55c29e732.jpeg)

The action as it should be (and how it was displayed when creating the schedule):
![FBDF5C7D-57C9-4A72-842A-7EEA211B1D31](https://user-images.githubusercontent.com/61377476/150011615-6730dcb4-4387-4547-a353-869946e02eec.jpeg)

**Comment by gvssr** [comment]
Additionally, the schedule entity according to Developer Tools:

```
weekdays:
  - mon
  - tue
  - thu
  - fri
times:
  - '08:00:00'
  - '12:00:00'
  - '13:00:00'
  - '15:00:00'
  - '16:00:00'
actions:
  - service: script.generic_component_climate
    entity_id: climate.studiekamer_radiator
    service_data:
      climate:
        entity_id: climate.studiekamer_radiator
      mode: Comfort
  - service: script.generic_component_climate
    entity_id: climate.studiekamer_radiator
    service_data:
      climate:
        entity_id: climate.studiekamer_radiator
      mode: Away
  - service: script.generic_component_climate
    entity_id: climate.studiekamer_radiator
    service_data:
      climate:
        entity_id: climate.studiekamer_radiator
      mode: Eco
current_slot: 4
next_slot: 0
next_trigger: '2022-01-20T08:00:00+01:00'
tags:
  - Heater
icon: mdi:calendar-clock
friendly_name: Studiekamer Radiator - Set Mode

```

**Comment by nielsfaber** [comment]
I did some local testing, I found that the issue is caused by the formatting of your service data.
Replace:
```yaml
        service_data:
          climate: 
            entity_id: climate.studiekamer_radiator 
```
By:
```yaml
        service_data:
          entity_id: climate.studiekamer_radiator
```

Scheduler does not handle a struct inside a struct for service_data. 
In other words, service_data must be limited to a list of properties with values, but a value cannot be another list of properties, but should be text/number etc.

I have am not planning to fix this, since it is easy to work around, and HA services (almost) never use service_data which contains multiple layers. 
Note that I am hesitant to touch this part of the code as it is one of the most complicated parts of the card (calculating back a matching action configuration from the service data). If it was a quick-fix I wouldn't have mind it.
