### ISSUE TITLE
Allow to group only in options

### ISSUE THREAD

**Issue by soloam** [nielsfaber/scheduler-card#506]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I use this card to allow people that don't know what an Home Assistant automation is, to schedule basic tasks. One of them is o start my roomba. I have one card for each action (for example, I have other that only shows my climate systems).

I have this card:

```yaml
type: custom:scheduler-card
discover_existing: false
include:
  - vacuum.r2d2
title: true
time_step: 1
customize:
  binary_sensor.anyone_home:
    name: Anyone Home
    states:
      - 'on'
      - 'off'
```
I only pretend to show the roomba in the first screen. And then in the options all my options to this schedule. On this casa, only a sensor that states if anyone is home or not!

If I go into options I see:

![image](https://user-images.githubusercontent.com/11949987/150315269-d9635d45-c3b0-473f-9521-d32c6d84222c.png)

And this is my problem. My family does not have a clue what a "Binary Sensor" is! I would prefere to group the sensors in groups. Similar to the groups in the first screen. The problem is that is I configure the groups I see them in both.

```yaml
type: custom:scheduler-card
discover_existing: false
include:
  - vacuum.r2d2
title: true
time_step: 1
groups:
  - name: When to Do
    icon: hass:ceiling-light
    include:
      - binary_sensor.anyone_home
customize:
  binary_sensor.anyone_home:
    name: Anyone Home
    states:
      - 'on'
      - 'off'
```

![image](https://user-images.githubusercontent.com/11949987/150316795-f5057a01-0811-445d-a7d9-46124251b24b.png)

I only would like to have "When To Do" in the options!

Is this possible?

Thank you

### Additional info

It should not display display "When To Do" in the first screen, only in the options!
