### ISSUE TITLE
Ability to schedule service calls not linked to an entity

### ISSUE THREAD

**Issue by mithomas** [nielsfaber/scheduler-card#514]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

As of now, the scheduler card allows for setting up schedules/schemes to set states or call services based on entities (i.e. `light.turn_on` as given in the documentation).

I'd like to be able to call a generic service which is not linked to an entity (specifically I want to use it to simply schedule reboots of my [Velux gateway](https://www.home-assistant.io/integrations/velux/) via the service `velux.reboot_gateway` but this could be used for similar ones like `fritz.reboot` or even `hassio.host_reboot` as well).

### Additional info

My current alternative is to do this via an automation:

```
- id: infra_reboot_klf
  alias: KLF reboot
  description: reboots the KLF200 in order to avoid TLS handshake issue
  trigger:
    - platform: homeassistant
      event: shutdown
    - platform: time
      at: "02:00:00"
  action:
    - service: velux.reboot_gateway
```
