### ISSUE TITLE
Feature request: add scripts

### ISSUE THREAD

**Issue by nagyrobi** [nielsfaber/scheduler-card#52]
Please add a group to start scripts using the scheduler. To be able to use your [suggestion](https://github.com/nielsfaber/scheduler-card/issues/24#issuecomment-692659199).
Please provide examples on how to provide variables from the scheduler to the script.

**Comment by anarro** [comment]
Hi, 

This is my config...


```
discoverExisting: false
domains:
  cover:
    actions:
      - icon: window-shutter-open
        service: open
      - icon: window-shutter
        service: close
      - icon: window-shutter-alert
        name: set position
        service: set_cover_position
        variable:
          field: position
          name: Position to
          showPercentage: true
  light:
    actions:
      - icon: lightbulb-off
        service: turn_off
      - icon: lightbulb-on-outline
        service: turn_on
        variable:
          field: brightness
          max: 255
          min: 0
          name: Brightness to
  scene:
    actions:
      - icon: play-box-multiple
        service: apply
  script:
    actions:
      - icon: play-box-multiple
        name: trigger
        service: turn_on
standardConfiguration: false
title: Custom Scheduler
type: 'custom:scheduler-card'

```

and work fine!
