### ISSUE TITLE
Allow passing of selected entity_id into action scripts

### ISSUE THREAD

**Issue by chriswood1001** [nielsfaber/scheduler-card#542]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Much like 'entity' can be used in display options, also allow the selected 'entity' to be referred to when calling a script.

Example use cases are:
  * Create a "turn on child 1 lights at 7AM" schedule for which we select "light.child1" to turn on at 7AM that calls "script.wake_up" passing along the "light.child1" entity_id. We can re-use this wake_up script for "turn on child 2 lights at 7AM".
  
  * Multi-zone HVAC homes can select "climate.upstairs" to call "script.warm_and_do_stuff" at 6AM which passes along the "climate.upstairs" entity ID. We can use this same script for "climate.downstairs" at 7AM.

  * Lawn irrigation can call "script.zone_lights_and_water_on" for "input_boolean.lawn_zone1" at 9PM, then use this same script for zone2 at 9:30 and zone3 at 10:00.

### Additional info

Propose to expose the Scheduler's selected entity as a variable, such as `'{{ entity_id }}` for use in script. In the case of multiple scheduler entities, expose them all as an array.

```
customize:
  light.*:
    actions:
      - service: script.my_script
        service_data:
          my_entity: '{{entity_id}}' # The ID of the entity selected from Scheduler > Group > Entity
        name: My script
```
