### ISSUE TITLE
More Display options available/possible?

### ISSUE THREAD

**Issue by emufan** [nielsfaber/scheduler-card#554]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

At first: More than great card (and integration). First I thought, Why, if I have already automations in HA, but then I started playing around. And esp. if I came to a point, where I thought "this and this would be great as well", it was already there.

I'm not sure, if it is a FR or already possible. What I would like to see in the overview, are more details about the job: The values of the set variables. Or to template the content, if first is not yet possible. With this workaround (perhaps the better one), I can take this from the generated attributes in the generated schedule entity as well.

Is it already possible (and I only didn't find it) or possible to have this in the future?

### Additional info

See proposal

**Comment by nielsfaber** [comment]
This is already possible.
For example, if you select action ‘heat’ for a thermostat entity in a schedule, the card will display ‘heat to XX’.
You can obtain the same result for any customization action by assigning a name for it such as:
> heat [to {temperature}]

here {temperature} will be replaced by the value set for the variable.
The part in [brackets] will be removed in case the variable is not set (hence action is called ‘heat’ until a temperature is assigned)

for more examples, see here: https://github.com/nielsfaber/scheduler-card/blob/main/src/localize/languages/en.json

**Comment by emufan** [comment]
Hm. Great that it is possible und thx for the fast response. But unfortunately, I diodn't get exactly, where I have to do what?

```
type: custom:scheduler-card
include:
  - script.rasenmahersteuerung_robonect
exclude: []
title: Rasemäher-Zeitplan
sort_by:
  - state
  - relative-time
show_header_toggle: false
time_step: 1
discover_existing: true
customize:
  script.rasenmahersteuerung_robonect:
    exclude_actions:
      - ausführen
      - ausschalten
      - einschalten
    actions:
      - service: script.rasenmahersteuerung_robonect
        name: Mähauftrag
        icon: mdi:robot-mower
        service_data:
          message: job
        variables:
          remotestart:
            name: Fläche
            options:
              - value: '2'
                name: Vor Garage
                icon: mdi:fire
              - value: '3'
                name: Vorne
                icon: mdi:snowflake
              - value: '4'
                name: Hinten
                icon: mdi:power
          duration:
            name: Mähdauer
            min: 5
            max: 120
            step: 5
display_options:
  primary_info: default
  secondary_info:
    - relative-time
    - days
    - time
    - Fläche [to {remotestart}]
  icon: action
```
Here remotestart is not displayed, but only "Fläche [to remotestart]"

Or do I have to modificate the source to add it?
