### ISSUE TITLE
Maxcio valve (tuya) not adjustable temperature

### ISSUE THREAD

**Issue by sminervini82** [nielsfaber/scheduler-card#635]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

V2.3.9

### Component Version

3.2.12

### Bug description

I can not set temperature bit only a range, but the valve not support it.

![Screenshot_20221202-141120](https://user-images.githubusercontent.com/119033105/205300627-7e035876-9c04-4e36-99cc-654969a6f9e8.jpg)

If I use it I get an error

![Screenshot_20221202-141419](https://user-images.githubusercontent.com/119033105/205300956-05fbb8b2-503a-4007-8578-20d1f2aea168.jpg)

I can set the valve temperature using climate.set_temperature

![Screenshot_20221202-141310](https://user-images.githubusercontent.com/119033105/205300757-961c2877-ba55-4eb6-8bc5-83e9cea459a4.jpg)

Thx for helping me

### Steps to reproduce

Try to set a scheduler on the valve, once start , it will give the error above

**Comment by sminervini82** [comment]
Possible solution:

If the device have hvac mode heat_cool (like mine) enable the same behaviour of hvac heat only.

I forced "hear" only in state of device, and cheduler works fine, until the device update and lost the "heat". Only mode.

In red what I manually added
![Screenshot_20221202-150829](https://user-images.githubusercontent.com/119033105/205311314-b0112723-cdcb-41ae-9965-8b17e0c5e506.jpg)

**Comment by nielsfaber** [comment]
Sorry, what is the bug exactly?
If your device supports mode `heat_cool`, it can be set with a min/max temperature range.
If it supports mode `heat`, it can be set with a single temperature.

**Comment by sminervini82** [comment]
Hi,
You are right, the bug is not in your application but have been created from who write the tuya integration for the heater valve....
They match 2 states to the heat_cool and no one to heat only, but the valve not support min/max temperature range but accept only the target temperature, and there are no sense to set heat_cool on this kind of device....

I add manually in the tuya application the correction and now in you scheduler I can select "heat" and all works fine.

Maybe this can be converted to "new feature" I try to explain:
If the  mode is "heat_cool" and the min and max temperature match, you can make a set temperature and not set the range.

**Comment by nielsfaber** [comment]
I will not make changes to the scheduler for your device. The change you are proposing may have negative consequences for other users.
I suggest you raise this bug in the owner for the tuya integration instead.

As a workaround you can remove the built-in action and add a custom action to the card via yaml configuration:
```yaml
customize:
  climate.my_tuya_thermostat: # replace with entity ID of your device
    exclude_actions:
      - regulate # remove the built-in action
    actions: # add the custom actions
      - service: set_temperature
        service_data:
          hvac_mode: heat_cool
        variables:
          temperature:
            min: 10
            max: 25
            step: 0.5
            unit: '°C'
        icon: 'mdi:fire'
        name: "heat[ to {temperature}]" # replace with local translation for 'heat' and 'to' if desired
```
