### ISSUE TITLE
Card blanks whole view in HA 2022.12

### ISSUE THREAD

**Issue by peteh** [nielsfaber/scheduler-card#646]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.0

### Component Version

3.2.14

### Bug description

I think it's not the same issue as https://github.com/nielsfaber/scheduler-card/issues/642

I have a view that contains the scheduler card. The view is essentially empty when the card is contained. When I remove the card the view is showing normally again. 
Screenshot of the blank view: 
![image](https://user-images.githubusercontent.com/918728/208769330-24d5d63a-64cb-4491-b49d-de655d32df5f.png)

Not sure how I can debug more, the docker container logs are empty I think. 

HA: 2022.12
Browser: Firefox

Here is the raw code of the view: 
```
views:
  - theme: Backend-selected
    title: Home
    type: custom:masonry-layout
    badges: []
    cards:
      - square: false
        columns: 2
        type: grid
        cards:
          - type: thermostat
            entity: climate.living_room_heater
          - type: thermostat
            entity: climate.office_heater
          - type: thermostat
            entity: climate.bedroom_heater
          - type: thermostat
            entity: climate.toilet_heater
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: input_boolean.automatic_heating
        show_state: true
      - type: entities
        entities:
          - entity: sensor.balcony_climate_temperature
          - entity: sensor.living_room_climate_temperature
          - entity: sensor.office_climate_temperature
          - entity: sensor.bedroom_climate_temperature
        show_header_toggle: false
      - type: custom:scheduler-card
        include:
          - climate.bedroom_heater
          - climate.living_room_heater
          - climate.office_heater
          - climate.toilet_heater
          - input_boolean.automatic_heating
        exclude: []
```

Any ideas what I could check? 
I tried: 
 * restarting HA
 * clearing browser cache
 * Try in Private mode of Firefox

### Steps to reproduce

Update to HA 2022.12
Update the card to 2.4.0
install the scheduler extension
Try to add the card to a view
Result: blank page

### Additional info
Maybe this console output from javascript helps: 
![image](https://user-images.githubusercontent.com/918728/208788306-baa3b4be-262e-4f6e-8cf2-fb87503e795d.png)

_No response_
