### ISSUE TITLE
Helpers as controllable entities

### ISSUE THREAD

**Issue by ipetrovits** [nielsfaber/scheduler-card#65]
Hi, Great work there!
I was wondering if that would be possible to add helpers (i.e. input_boolean, input_select) as controllable entities by scheduler?

**Comment by KTibow** [comment]
Read the docs, you can add custom actions.

**Comment by nielsfaber** [comment]
Try to add this to the card:
```
domains: 
  input_boolean:
    actions:
      - service: turn_on
      - service: turn_off
  input_select:
    actions:
      - service: select_option
        name: "set to my_option"
        service_data: {option: my_option}
```
