### ISSUE TITLE
Card not functional inside of a browser_mod popup

### ISSUE THREAD

**Issue by brianewman** [nielsfaber/scheduler-card#663]
### Checklist

- [ ] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.1

### Component Version

3.2.14

### Bug description

I'm not sure if this started with 2022.12 or 2023.1, but clicking/tapping on the schedules or add button of a scheduler card inside of a browser_mod popup does not do anything.  

The same card configuration works as expected as a top-level card and previously worked inside of a browser_mod popup.  Other (non-scheduler) cards work as expected inside of a browser_mod popup.  

### Steps to reproduce

I use a glance card configured as below (additional entities removed for clarity). 

```
type: glance
entities:
  - entity: light.front_porch_lights
    name: Outside
    show_state: false
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          deviceID: this
          content:
            type: vertical-stack
            cards:
              - type: entities
                state_color: true
                entities:
                  - entity: light.front_porch_lights
              - type: custom:scheduler-card
                include:
                  - light.front_porch_lights
                exclude: []
                discover_existing: false
                sort_by: state
                title: true
                show_add_button: true
                show_header_toggle: false
                time_step: 5
show_state: true
show_name: true
show_icon: true
columns: 5
```

Configure a card like above.  Replace "light.front_porch_lights" with any light or switch entity.
Click/tap on the icon to bring up scheduler card in a popup.  
Click/tap on Add button.
Nothing happens.

If schedules are created elsewhere for this entity, the schedules will show on the popup card, but clicking/tapping them does nothing.
