### ISSUE TITLE
Entities not selected when editing existing schedule

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-card#666]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.4.1

### Component Version

3.2.14

### Bug description

```ENTITY``` tab while editing existing schedule does not reflect actually/previously selected entities, as well ```Multiple``` status.

Just checked - it happens in both cases: when ```Multiple``` selected and when not.

### Steps to reproduce

See schedule card in lovelace:
![image](https://user-images.githubusercontent.com/15225823/213748514-462d1029-bb82-4f20-8016-37a5ccc36108.png)

Press on it to edit:
![image](https://user-images.githubusercontent.com/15225823/213748684-0a699a90-3e23-4d87-bfa5-90409a6138ea.png)

See list of entities ^^.

If I want to remove/add more entities - press ```ENTITY``` and see:
![image](https://user-images.githubusercontent.com/15225823/213748875-857632a8-6315-4b9b-8fed-6bc6c99897a3.png)

Selector ```Multiple``` not selected, entities not selected....
Need to remember list of entities from previous screen and select them all again.

Do i do smth wrong ?

### Additional info

Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.0
Frontend 20230110.0 - latest

**Comment by nielsfaber** [comment]
Strangely for me this problem does not occur.

Clicking on this item:
![image](https://user-images.githubusercontent.com/16861605/218844454-85610494-a43e-4878-a14b-0942d38badda.png)

Gives the editor dialog:
![image](https://user-images.githubusercontent.com/16861605/218844635-3ac22d4d-c51b-410b-ad05-cbca99e97f89.png)

Switching to the entity tab:
![image](https://user-images.githubusercontent.com/16861605/218844805-72962942-22a8-4dab-a669-bb09ec1ad745.png)

I don't really know what is different between your situation and mine, but if I cannot reproduce the issue I cannot solve it either I'm afraid. 
I tried also with switches, it gives the same results. 
Do you see this behaviour with any entity? Any clues on how to reproduce this?

**Comment by Masterz69** [comment]
Recently updated Core to fresh version. 
See same issue - with switch, alarm and climate entities.

![image](https://user-images.githubusercontent.com/15225823/219001508-58c464cf-f7d5-4143-aa99-83a32c199d06.png)

Pressing on ENTITY - see list of entities, but nothing selected.

![image](https://user-images.githubusercontent.com/15225823/219001693-bcb6aeac-221e-41e8-b86e-7103edfcf161.png)

Lovelace card config:
```
- type: entities
  show_header_toggle: false
  state_color: true
  entities:
    - entity: climate.entryr_floor
      name: 'Entry Room'
      icon: 'mdi:heating-coil'
    - entity: climate.kitchen_floor
      name: 'Kitchen'
      icon: 'mdi:heating-coil'
    - type: 'custom:scheduler-card'
      discover_existing: false
      time_step: 30
      title: false
      include:
        - climate.entryr_floor
        - climate.kitchen_floor
      display_options:
        primary_info: '{name}'
        secondary_info: '{action} - {relative-time}'
```

Scheduler card v3.2.7
Scheduler component v3.2.14
HA Core 2023.2.4
Browser Chrome 108.0.5359.125

What else can affect ?

P.S.
It working as expected and as You described in case of following card config:
```
type: custom:scheduler-card
title: true
standard_configuration: true
include:
  - '*'
```

And it my case is when include is defined list of entities, like
```
include:
  - climate.entryr_floor
  - climate.kitchen_floor
```
or
```
include:
  - alarm_control_panel.xg3_s_alarm
  - alarm_control_panel.xg3_h_alarm
  - alarm_control_panel.house
  - alarm_control_panel.shed
```
or 
```
include:
  - switch.lights_*
  - switch.light_*
  - sensor.slumi_overhang_illuminance_lux
  - sensor.season
  - sun.su
```
