### ISSUE TITLE
Features request: (1) Setting AC mode & temperature together, (2) Automatic selection of group and entity

### ISSUE THREAD

**Issue by mottibz** [nielsfaber/scheduler-card#67]
Following our communication, it will be great to have:
(1) When adding an item, have an action to set both the AC mode and temperature together.
(2) When defining a card per AC (each AC unit will have its own card), when adding an item, automatically select climate and the specific entity, and go directly to selecting the action.
Thanks!

**Comment by nielsfaber** [comment]
> (2) When defining a card per AC (each AC unit will have its own card), when adding an item, automatically select climate and the specific entity, and go directly to selecting the action.

This part is done. You should see this behavior already.

The other request will have to wait a while longer

**Comment by nielsfaber** [comment]
Sorry about the changes. But it was needed because a lot of people found it very confusing.
Try this:
```yaml
type: 'custom:scheduler-card'
title: Timers
discover_existing: false
include:
  - climate.iotti_ac_basement
```
It should give you the same functionality.
