### ISSUE TITLE
Climate entities being weird

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-card#707]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.9

### Component Version

v3.2.15

### Bug description

I had a previously working schedule using heat/cool mode on my thermostat, but when I went to check on it, I saw "???". When I tried to set one to heat/cool mode again, the only slider was "temperature" (not how heat/cool mode works). Then 3 different heat/cool modes appeared.
Right now, the only issue affecting me is the duplicate heat/cool modes:
![image](https://github.com/nielsfaber/scheduler-card/assets/10727862/1641e9e7-ff99-4603-8658-6b3f2e47a195)

### Steps to reproduce

1. Make a new schedule with a thermostat
2. Choose scheme
3. Choose a slot
4. Choose heat/cool mode

**Comment by KTibow** [comment]
This seems to depend on whether the climate entity is already in heat/cool mode. FYI the climate entity comes from the Kumo integration.

**Comment by nielsfaber** [comment]
Hi Kendell, long time no see!

> I had a previously working schedule using heat/cool mode on my thermostat, but when I went to check on it, I saw "???".

In your screenshot this is not visible, did this solve itself?

> When I tried to set one to heat/cool mode again, the only slider was "temperature" (not how heat/cool mode works). 

Agreed that this is not what should happen.
Could you post a screenshot of the properties of this climate entity under dev tools?

> Then 3 different heat/cool modes appeared. Then 3 different heat/cool modes appeared.

This suggests that previously created actions are not longer supported by the entity.
They are imported from the schedule and do not merge with the action which was calculated by the card.
I am suspecting that some settings of your climate device have changed.
Do you have any idea about when the schedule was originally created and when the issues started?

> This seems to depend on whether the climate entity is already in heat/cool mode.

You are suspecting that the actions showing up in the card are depending on the current state of the climate entity?

Apart from all issues you pointed out, I'm also noticing that the markers indicating the start/stop times of your timeslots are in a wrong position. They are supposed to be placed above the slider handle. Is this problem occurring for all your schedules? Which browser are you using?

**Comment by KTibow** [comment]
I'm in Firefox. The markers stay in the same place when I scroll, which is how they got there.
I can currently reproduce the 3x heat/cool, and the singular temperature based on the current mode, but not the ???. I sent a recording showing what I'm talking about on the HA Community forums.
As for the climate entity (state heat_cool):
```
hvac_modes: off, cool, dry, heat, fan_only, heat_cool
min_temp: 45
max_temp: 95
fan_modes: quiet, low, powerful, auto
current_temperature: 65
temperature: null
target_temp_high: 74
target_temp_low: 68
current_humidity: 54
fan_mode: auto
hvac_action: idle
filter_dirty: false
defrost: false
rssi: -49
runstate: normal
friendly_name: Tree House
supported_features: 11
```

**Comment by KTibow** [comment]
Worryingly the scheduler component just set my climate entity so it has a minimum of 75 degrees and maximum of 74, resulting in my home heating up. I'm going to go set up some automations instead out of concern.

**Comment by nielsfaber** [comment]
I found out that scheduler has issues with climate entities which set their `temperature` / `target_temp_high` / `target_temp_low` settings to 'null'.
The card checks whether these properties exist (and are not null) to determine whether the device supports setting a setpoint range or single setpoint.

I think this explains the behaviour you experienced:
> This seems to depend on whether the climate entity is already in heat/cool mode. FYI the climate entity comes from the Kumo integration.

I made a change to only require the properties to exist, regardless of their value. 
I assume this will also solve the issues of the multiple heat/cool actions and unrecognized actions `???`.

Regarding to the markers being out of place, I noticed this occurs in case the window is so small that the dialog does not fit in the height (and thus a scrollbar shows up). I tried a couple of things to make it work with scrolling, but couldn't fix this. I will see if I can tackle this at a later point.

Regarding
> Worryingly the scheduler component just set my climate entity so it has a minimum of 75 degrees and maximum of 74, resulting in my home heating up. 

Could you share the properties of the schedule under developer tools / states?
The service call performed by scheduler should be directly visible like so:
![image](https://github.com/nielsfaber/scheduler-card/assets/16861605/b65ba639-55bf-4cfe-bd17-5a0dd1954cc2)

**Comment by nielsfaber** [comment]
I just released v3.2.10 of the card, I suggest to update to this version to solve the issue with the heat/cool action showing up wrongly.

**Comment by KTibow** [comment]
Okay, I just made a new scheme:
```
weekdays: daily
timeslots: 06:00:00 - 08:00:00, 08:00:00 - 18:00:00, 18:00:00 - 20:00:00, 20:00:00 - 00:00:00
entities: climate.tree_house
actions: 
- service: climate.set_temperature
  data:
    hvac_mode: heat
    temperature: 66
- service: climate.set_temperature
  data:
    hvac_mode: heat_cool
    target_temp_low: 68
    target_temp_high: 74
- service: climate.set_temperature
  data:
    hvac_mode: cool
    temperature: 70
- service: climate.set_temperature
  data:
    hvac_mode: heat_cool
    target_temp_low: 62
    target_temp_high: 68

current_slot: 0
next_slot: 1
next_trigger: 2023-06-17T08:00:00-07:00
tags: 
icon: mdi:calendar-clock
friendly_name: Schedule #7ae965
```
As for the problem with sticking while scrolling, personally I would recommend making a parent `relative` and then adjusting the positioning of the `absolute` element to fit.
Anyway I think some of the problem is just that the Kumo integration is finnicky. Is some sort of calling a service multiple times possible with the scheduler integration?
