### ISSUE TITLE
Add support for shell_command

### ISSUE THREAD

**Issue by paoloantinori** [nielsfaber/scheduler-card#719]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Add support for `shell_command` entities

### Additional info

https://www.home-assistant.io/integrations/shell_command/

From the developer console they are invoked directly, just like a `script`:

```yaml
service: shell_command.my_shell_command
data: {}
```

Working steps to add a scheduler via the service:

```yaml
service: scheduler.add
data:
  weekdays: daily
  repeat_type: single
  name: my_shell_command
  timeslots:  [{start: "17:06", actions: [{service: "shell_command.my_shell_command"}]}] 
```
