### ISSUE TITLE
Make it possible to show the time bar as a UI elemeny

### ISSUE THREAD

**Issue by pdwonline** [nielsfaber/scheduler-card#767]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

I love this component.  Most interesting is the easy schedule overview that represents a time bar: very visual!
I would love to see that as a UI element that I could include in a lovelance view, without the other options, like this:

<img width="269" alt="afbeelding" src="https://github.com/nielsfaber/scheduler-card/assets/6775870/2e5fd9e7-0194-4c6a-8d54-2b51a9830179">

### Additional info

If I could add a sceduler bar card for a schedule it gives a good overview instead of a list. Optionally, users might change times and or add/remove actions without modifying other options

**Comment by Schmu1605** [comment]
yes that would be fine

**Comment by auriga-mi** [comment]
That's actually what I was about to post as feature proposal, the setup with the bar is a really great UI, would love to use the same one as read-only on the dashboard 😄

**Comment by u20p17** [comment]
+1 exactly what I am looking for :)

**Comment by Ga-Re** [comment]
+1 would be a nice addition

**Comment by jarthod** [comment]
Also +1 for me on this one, it would be a great addition (either as an option or different card type).

**Comment by pdwonline** [comment]
> Remove stale label or comment or this will be closed in 7 days

How?

**Comment by lublak** [comment]
@pdwonline hi I hope it's okay to ask you here. How it's done that you using schema based heating option. Currently I can only change the temperature. You have options: Spaarstand, Comfort and Eco. I think it's more useful. I would love to do it like this!

**Comment by lublak** [comment]
@pdwonline thanks for the answer <3
This has already helped me a lot. Now I just have to find out how to change the thermostats when the input_select changes. I think the best solution is an automation:
![grafik](https://github.com/nielsfaber/scheduler-card/assets/44057030/78e4db99-2bef-4c2a-bd3d-cdefacf18b26)

**Comment by pdwonline** [comment]
>  I think the best solution is an automation:

here you have my automation. I use it as a package, so both helper and automation are there

````
package_climate_kitchen:
# BASE ID: KITCHEN_CLIMATE_
# PDW 2023-12, V1

# -- COMPONENTS
  climate:
  - platform: generic_thermostat
    name: thermostat_kitchen
    unique_id: KITCHEN_CLIMATE_03
    heater: switch.radiator_kitchen
    target_sensor: sensor.temperature_kitchen
    min_temp: 10
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.5

  input_select:
    thermostatmode_kitchen:
      name: Thermostaatmodus Keuken
      icon: mdi:home-thermometer-outline
      options:
        - Eco
        - Comfort
        - Spaarstand
        - Aangepast
        - Uit

  input_number:
    temperature_kitchen:
      name: Thermostaat Keuken
      min: 0
      max: 25
      step: 0.5
      mode: box
      unit_of_measurement: '°C'
      icon: mdi:home-thermometer-outline

  sensor:
  - unique_id: KITCHEN_CLIMATE_02
    name: temperature_avg_kitchen
    platform: group
    type: mean
    ignore_non_numeric: true
    device_class: temperature
    entities:
      - sensor.temperature_kitchen

  template:
    - unique_id: KITCHEN_CLIMATE_04
      sensor:
      - name: "temperature_req_kitchen"
        icon: mdi:thermometer-plus
        device_class: temperature
        unit_of_measurement: '°C'
        state: >
          {%- set raw_req=(states("input_number.temperature_kitchen") | float(0) - states("sensor.temperature_avg_kitchen") | float(0)) | round(1)-%}
          {%- if raw_req > 0 -%}{{raw_req}}{%- else -%}0{%- endif -%}
      trigger:
      - platform: state
        entity_id: sensor.temperature_avg_kitchen
      - platform: state
        entity_id: input_number.temperature_kitchen

# -- AUTOMATIONS
  automation:
  # -- Thermostat sync kitchen --
  - id: KITCHEN_CLIMATE_05
    alias: Thermostat_sync_kitchen
    description: Sync thermostat kitchen
    mode: parallel
    max: 10

    variables:
      thermostat_modes:
      -  mode: Eco
         temp: '{{ states("input_number.temperature_eco") |float(0) -1 }}'
      -  mode: Comfort 
         temp: '{{ states("input_number.temperature_comfort") |float(0) -1 }}'
      -  mode: Spaarstand 
         temp: '{{ states("input_number.temperature_low") |float(0) -1 }}'
      -  mode: Uit 
         temp: 10
      matched_temp: >-
           {{ thermostat_modes
                | selectattr('mode', 'eq', states('input_select.thermostatmode_kitchen'))
                | map(attribute='temp')
                | list |first |float(0) | default(0) }}
      matched_mode: >-
          {{ thermostat_modes
              | selectattr('temp', 'eq', states('input_number.temperature_kitchen') |float(0) )
              | map(attribute='mode')
              | list |first |default('none') }}

    trigger:
      - platform: state
        entity_id:
          - input_number.temperature_kitchen
        id: temp_kitchen
      - platform: state
        entity_id:
          - input_select.thermostatmode_kitchen

    condition: []
    action:
      - service: logbook.log
        data:
          name: Thermostat Sync
          message: 'Kitchen mode {{states("input_select.thermostatmode_kitchen")}} matched: {{ matched_mode }} (temp {{ matched_temp }})'

      - if:
        # Temperature input
        - condition: trigger
          id: temp_kitchen

        then:
          # turn off below 10
          - if:
            - condition: template
              value_template: '{{ states("input_number.temperature_kitchen") |int(0) < 10 }}'
            then:
            - service: input_number.set_value
              target:
                entity_id: input_number.temperature_kitchen
              data:
                value: '10'

          # set thermostat temp
          - if:
            - condition: template
              value_template: >-
                {{ 
                  states("input_number.temperature_kitchen") |float(0) != state_attr("climate.thermostat_kitchen","temperature") |float(0) 
                }}
            then:
            - service: climate.set_temperature
              data:
                temperature: '{{ states("input_number.temperature_kitchen") |float(0) |round(2) }}'
                hvac_mode: heat
              target:
                entity_id: climate.thermostat_kitchen

          # Try to match and set modus based on temp
          - delay:
              seconds: 0.2

          - if:
            - condition: template
              value_template: '{{ matched_mode != "none"}}'
            then:
            - if:
              - condition: template
                value_template: '{{ matched_mode != states("input_select.thermostatmode_kitchen") }}'
              then:
              - service: input_select.select_option
                target:
                  entity_id: input_select.thermostatmode_kitchen
                data:
                  option: '{{ matched_mode }}'
            else:
              - condition: template
                value_template: >-
                  {{ states('input_select.thermostatmode_kitchen') != "Aangepast" }}
              - service: input_select.select_option
                target:
                  entity_id: input_select.thermostatmode_kitchen
                data:
                  option: 'Aangepast'

        else:
        - delay:
            seconds: 0.2

         # trigger by selection
        - if:
          - condition: template
            value_template: >
              {{ 
                states("input_number.temperature_kitchen") |float(0) != matched_temp |float(0)
              }}
          then:
          - service: input_number.set_value
            target:
              entity_id: input_number.temperature_kitchen
            data:
              value: '{{ matched_temp |float(0) }}'

      - if:
        - condition: template
          value_template: >
            {{ 
              states("input_select.thermostatmode_kitchen") != "Uit" 
              or states("input_number.temperature_kitchen") |float(0) > 10
            }}
        then:
          # Set HVAC mode when Auto
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.thermostat_kitchen
            data:
              hvac_mode: 'heat'
        else:
          # turn if off completely
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.thermostat_kitchen
              data: 
                hvac_mode: 'off'
            - service: switch.turn_off
              target:
                entity_id: switch.radiator_kitchen

````

the ui looks like this 
<img width="216" alt="afbeelding" src="https://github.com/nielsfaber/scheduler-card/assets/6775870/5daae580-2606-4d56-a571-31ce9f29fc05">
