### ISSUE TITLE
Bug with custom actions and schedule where the actions don't appear

### ISSUE THREAD

**Issue by lucas-dumartin** [nielsfaber/scheduler-card#778]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.12

### Component Version

v3.2.15

### Bug description

After I added custom `actions` with the `customize` keyword in the yaml and using them the following is happening :

When I want to edit the Scheme :
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/b0ffca35-b72c-4535-886f-c2675b9f9a13)

And I click on a time period with a custom action no other action value is proposed
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/5a9889e5-22d0-4ac1-af37-366a2f566c14)

But if I add a new period with no custom action assigned I get the proposition for all the actions possible:
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/f1a85763-27de-4a35-ae73-b9d6d576205f)

### Steps to reproduce

On a scheduler card add the following customize for lights :
```yaml
customize:
  light:
    actions:
      - service: turn_on
        service_data:
          brightness: 50
        name: Conforting Light
        icon: mdi:lightbulb-on-40
      - service: turn_on
        service_data:
          brightness: 100
        name: Fully Lit Up
        icon: mdi:lightbulb-on
```

Then add an entry for a light and select "Make a scheme" :
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/630f87d7-c5a8-41ab-802a-3126d1a292b2)

Add an action for each time period :
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/ae970b84-2b2c-4d54-9ffb-c95961d0197a)

Save then click on it to edit it again and you should not have any action proposition when you select a time period :
![image](https://github.com/nielsfaber/scheduler-card/assets/23265822/36ca1d93-9bff-4783-a82b-9bb773b590c1)

You can make them re appear by adding and deleting a new time period

**Comment by lucas-dumartin** [comment]
Just found out that a fix is possible by changing the custom action with a `%` at the end of the values :

```
customize:
  light:
    actions:
      - service: turn_on
        service_data:
          brightness: 50%
        name: Conforting Light
        icon: mdi:lightbulb-on-40
      - service: turn_on
        service_data:
          brightness: 100%
        name: Fully Lit Up
        icon: mdi:lightbulb-on
```

But the bug still remains if the % is not added at the end of the values
