### ISSUE TITLE
How to do a proper customisation for a radiator thermostat - the default one did not work out ?

### ISSUE THREAD

**Issue by typxxi** [nielsfaber/scheduler-card#874]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I was unable to open another topic on the ha forum topic but I have written everything when I wanted to save. You can only write 2 replies which I had done to a previous topic without getting a reply therer. So I could not post it over there .

Another reason to open the discussion forum here for sure where I would be able to ask this question too.

How can i limit the settings for a new schedule on a thermostat to

"automatic" only and the **heating option activated** , 

I want to hide "ausschalten / turn off" and  "heizen- kühlen / heating - cooling" options which I do not need on a radiator.

And when I press automatic I want to have **set the temperature option** settings **on** to only have to adjust the temperature.

![image|533x499](upload://qBeSIjxA3QSXTsNBwsigwncXG39.png)

I know it must have to do with the customize sections but my first attempt here did not work out and I did not find the radiator thermostat only settings or an example for that.

```
customize:
  climate.thermostat_1_kaminzimmer:
    name: KAMINZIMMER
    icon: thermometer
    actions:
      - service: set_hvac_mode
        name: Set mode
        icon: hass:settings
        variables:
          hvac_mode:
            name: Operation mode
            options:
              - value: heat
                icon: hass:fire
```

any suggestions.

### Actual behavior
shows all options which I can not use cause I can not cool and I can not turn off. 

### Steps to Reproduce
as shown above the default feature
