### ISSUE TITLE
Climate min_temperature not taken into account

### ISSUE THREAD

**Issue by mrzv** [nielsfaber/scheduler-card#882]
### Checklist

- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.13

### Component Version

3.3.8

### Bug description

I have the following in my climate component config (ESPHome):
```
climate:
  - platform: mitsubishi_itp
    ...
    visual:
      min_temperature: 13
      max_temperature: 26
      temperature_step:
        target_temperature: 0.9
        current_temperature: 0.1
```

This makes it so the thermostats change by 0.9 degrees F, and at 68 F (20 C) they show 68.

With this configuration, the scheduler card does change by 0.9 degrees, but around 68, it shows 68.4 F. The lowest temperature it allows to set is 55.8 F (~13.222 C), so I assume that's the culprit.

### Steps to reproduce

Change climate configuration as above, go into scheduler card, try to set a temperature for a scheme.
