### ISSUE TITLE
More conditions for time/date

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-card#900]
### Checklist

- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.
- [x] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Have following sensors:
```yaml
  sensor:
    - platform: time_date
      display_options:
        - 'time'
        - 'date'
        - 'time_date'
```

Then using `sensor.time` in lovelace card: 
```yaml
          - type: entities
            show_header_toggle: false
            state_color: true
            entities:
              - type: 'custom:scheduler-card'
                discover_existing: false
                time_step: 15
                title: false
                include:
                  - switch.lights_*
                  - sensor.time*
                exclude:
                  - switch.*garland*                
                display_options:
                  primary_info: '{name}'
                  secondary_info: '{action} - {relative-time}'
```

While creating schedule - only conditions for `sensor.time` is `equal`/`not equal`.

![Image](https://github.com/user-attachments/assets/225ae66f-bb1d-4d25-a114-b0988fff150b)

### Additional info

Kindly asking to add more conditions, like `before`/`after`, as well really appreciate to have time/date inputs versus current free-text `state` input.

Thank You very much.
