### ISSUE TITLE
Include domains in group section is not working

### ISSUE THREAD

**Issue by shevu** [nielsfaber/scheduler-card#96]
I heave this code:
```
groups:
  - icon: ceiling-light
    name: My Scripts
    include:
      - script
    exclude:
      - script.script_excluded
  - icon: ceiling-light
    name: My Scenes
    include:
      - scene
  - icon: ceiling-light
    name: My Outputs
    include:
      - switch
    exclude:
      - switch.excluded
time_step: 1
type: 'custom:scheduler-card'
include: []
```

In HA i ahve created sth. about 12 scripts. When I want to add schedule I see nothing in "My scripts" section.

In previous versions it worked good.

**Comment by nielsfaber** [comment]
Please edit your message. I cannot read the code.

**Comment by nielsfaber** [comment]
Thanks for updating.
Your `include: []`  is an empty list.
So you will have no entities in your card.
The groups only filter from within the entities in your card.

It means for you that you will have to add the combined includes and excludes lists of all your groups to the card.
I might change it in the future, but currently it works like that.

**Comment by shevu** [comment]
Ok. for now I have to use something like this - it is working:
```
groups:
  - icon: ceiling-light
    name: My Scripts
    include:
      - script
  - icon: ceiling-light
    name: My Outputs
    include:
      - switch
time_step: 1
type: 'custom:scheduler-card'
include:
  - switch
  - script
exclude:
  - script.script1
  - script.script2
  - switch.ref1
  - switch.ref2

It is strange little bit but it's working


```
